### ISSUE TITLE
How to get the total and used space of google drive

### ISSUE THREAD

**Issue by nitesh-varma** [gimite/google-drive-ruby#104]
How to get the total and used space of google drive, 
like can be get from https://developers.google.com/drive/v2/reference/about/get

<pre>
  drive = client.discovered_api('drive', 'v2')
  result = client.execute(
    :api_method => drive.about.get)
</pre>

Please suggest, I had integrated google-drive-ruby in my rails application but didn't getting way to get space using google-drive-ruby.

Waiting for valuable reply as soon as possible.

Thanks & Regards,
Nitesh V

**Comment by do11** [comment]
Please add Session#about() method for easy access to quota sizes. It's short but useful.

```
class GoogleDrive::Session
  def about
    api_result = execute!(:api_method => self.drive.about.get)
    return api_result.data
  end
end

# usage:
about = session.about
p [about.quota_bytes_total, about.quota_bytes_used]
```
