### ISSUE TITLE
Take up large memory to load worksheet

### ISSUE THREAD

**Issue by jookeing** [gimite/google-drive-ruby#113]
session = GoogleDrive.login_with_oauth(access_token)
spreadsheet = session.spreadsheet_by_key(url_key)
ws =spreadsheet.worksheets[0]
The problem occurs when i m trying to read any info from worksheet such as ws[1,1].
It will take up GB memory to load a large worksheet which contains 8k row with 30 columns.

**Comment by PatrickBOConnell** [comment]
I am having the same issue as jookeing. I have a very large worksheet that has 27k rows and 27 columns. Is there a way to update a row in the worksheet without loading the whole worksheet into memory first? Like being able to make a change to a row and save it to google all in one step?

**Comment by gimite** [comment]
Thanks for the code. With your new method, you can write, but not read, the spreadsheet, without consuming large memory. So I'm wondering what would be the use case where this is useful. In your case, how do you read the spreadsheet? Do you read the spreadsheet with the normal Web UI at spreadsheet.gogle.com? Also, how do you know the number 7213, the row you should write to?
