### ISSUE TITLE
Support passing oauth2 auth token directly

### ISSUE THREAD

**Issue by rceee** [gimite/google-drive-ruby#12]
I'm using Omniauth-google-oauth2 to authenticate a user logging into my app, and I store their token (from [omniauth.auth][credentials][token].  It starts with ya29.blahblahblah.  I pass this to the login_with_oauth function, but keep getting this error.  How come?

**Comment by akash-cp** [comment]
How do we refresh access token when it is expired using only omniauth hash?

**Comment by gimite** [comment]
If you have refresh_token, you can get a new access_token with the second sample code here, for example:
http://www.rubydoc.info/gems/google_drive/GoogleDrive#login_with_oauth-class_method

The sample code uses google-api-client library. You can alternatively use omniauth to do something similar, I guess, but I don't know how to do that exactly.
