### ISSUE TITLE
Google shutting down Documents List API

### ISSUE THREAD

**Issue by stevebooks** [gimite/google-drive-ruby#128]
I just an email from Google saying they are going to be shutting down the Documents List API. They suggest the following:
```
Determine if you have an application that makes requests to these types of URLs:

https://docs.google.com/feeds/
https://docs.googleusercontent.com/
https://spreadsheets.google.com/feeds/

Migrate the applications to Drive API.

```
Will this gem be broke with these changes? It looks like they are happening on April 20th.

**Comment by gimite** [comment]
We have switched to Google Drive API with google_drive ver. 1.0.0. So it should be fine if you use ver. 1.0.0. Note that some incompatibilities were introduced in ver. 1.0.0, which is documented here:
https://github.com/gimite/google-drive-ruby#incompatibility-introduced-in-ver-100

We still use https://spreadsheets.google.com/feeds/ , but I believe it's not part of the deprecation.
https://developers.google.com/google-apps/spreadsheets/
says nothing about deprecation. Is your quote from the email directly from Google? Can you paste the whole content of the email?

**Comment by gimite** [comment]
Hm I believe they included https://spreadsheets.google.com/feeds/ in the list by mistake, but let me confirm.

**Comment by gimite** [comment]
Official statement that https://spreadsheets.google.com/feeds/ is actually not deprecated:
https://code.google.com/a/google.com/p/apps-api-issues/issues/detail?id=3709

**Comment by stevebooks** [comment]
Thanks :+1:
