### ISSUE TITLE
"google_drive_v0" is missing on rubygems.org

### ISSUE THREAD

**Issue by tricknotes** [gimite/google-drive-ruby#130]
[`README.md`](https://github.com/gimite/google-drive-ruby/tree/v1.0.0#incompatibility-introduced-in-ver-100) says "google_drive_v0" is the previous version of 'google_drive' gem.
But https://rubygems.org/gems/google_drive_v0 is not found...

Could you publish "google_drive_v0" or fix README.md using 'google_drive' 0.3.x ?

**Comment by gimite** [comment]
It's shipped with google_drive gem. So you should:

    gem install google_drive

then

    require "google_drive_v0"

I agree it's a bit confusing... I will clarify it in the README.

Note that the backend API of google_drive_v0 is already deprecated, and may not be available after April this year.

**Comment by tricknotes** [comment]
Ah, that's right.
This was my misreading.

Thank you for letting me know.
