### ISSUE TITLE
Undefined method 'drive' when trying to list files

### ISSUE THREAD

**Issue by djvs** [gimite/google-drive-ruby#131]
undefined method `drive' for nil:NilClass

    /usr/local/rvm/gems/ruby-2.2.0/gems/google_drive-1.0.0/lib/google_drive/session.rb:101:in `drive'
    /usr/local/rvm/gems/ruby-2.2.0/gems/google_drive-1.0.0/lib/google_drive/session.rb:126:in `files'

after being called from:

      results = @session.files.map{|x|{title: x.title}}

**Comment by gimite** [comment]
How did you create `@session`?
