### ISSUE TITLE
Encoding::UndefinedConversionError: "\xE2" from ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by ocouronne** [gimite/google-drive-ruby#132]
I am getting a Encoding::UndefinedConversionError: "\xE2" from ASCII-8BIT to UTF-8 error after a ws.export_as_file. That is happening on a file that used to work up to just now. This is V1. I don't think that it is similar to #107.

**Comment by ocouronne** [comment]
I removed the ™, ®, and other – and it works now. This used to work before just fine, but somehow it stopped.

**Comment by gimite** [comment]
Thanks for the report and sorry for late. There was a bug handling multi-byte characters. Fixed in the repository.

**Comment by ocouronne** [comment]
Awesome, thank you very much for fixing this.
