### ISSUE TITLE
Spreadsheet encoding issues

### ISSUE THREAD

**Issue by d3zorg** [gimite/google-drive-ruby#135]
When spreadsheet contains only latic chracters - it works fine, but when there are some cyrillic text in original file, then my script puts some wierd encoding like ibm437 with "╨í╨╝╨╛╨╗╨╡╨╜╤ü╨║" instead of "Смоленск" for example. How can I handle it?
```ruby
 require 'google/api_client'
  require 'google_drive'

  client = Google::APIClient.new(
      :application_name => 'MyApp',
      :application_version => '0.0.1'
  )
  auth = client.authorization
  # Follow "Create a client ID and client secret" in
  # https://developers.google.com/drive/web/auth/web-server to get a client ID and client secret.
  auth.client_id = "client_id"
  auth.client_secret = "client_secret"
  auth.scope =
      "https://docs.google.com/feeds/ " +
          "https://docs.googleusercontent.com/ " +
          "https://spreadsheets.google.com/feeds/"
   auth.redirect_uri = "http://example.com/redirect"

   auth.refresh_token = "refresh_token"
   auth.fetch_access_token!
   session = GoogleDrive.login_with_oauth(auth.access_token)

  puts session.inspect

  sh = session.spreadsheet_by_key("spreadsheet_key")

  sh.worksheets[0].export_as_file("temp.csv")
```

**Comment by gimite** [comment]
Thanks for the report. I have just pushed google_drive gem ver. 1.0.1, which includes a fix for export_as_file #132 . But I'm not sure if it's relevant to your issue. Can you try it? If there is still the issue, can you point me an example spreadsheet and the exported CSV file? 

Also, can you try to export it in Google Spreadsheet web UI? Note that the CSV file should be encoded in UTF-8 (both via web and export_as_file), which is different from what Excel expects.
