### ISSUE TITLE
BadRequestException trying to get collection_by_title on folder name

### ISSUE THREAD

**Issue by tomay** [gimite/google-drive-ruby#142]
I am able to open a session and get individual spreadsheets by key, but I cannot get a folder by title using:  
    `folder = session.collection_by_title(folder_name)`

I get the following error:  
    `The Doclist API has been shut down. Please use the new Drive API, https://developers.google.com/drive/.`

I would like to get all of the spreadsheets in the folder and not have to list them one by one. Is this no longer supported? 

My auth scope is
"https://www.googleapis.com/auth/drive https://spreadsheets.google.com/feeds/ https://docs.googleusercontent.com/ https://docs.google.com/feeds/"

**Comment by Nawshine** [comment]
Is there a new gem you recommend that supports Folders?

**Comment by yhjor1212** [comment]
I may consider gem switching to Google API gem if they are not updating it

**Comment by gimite** [comment]
session.collection_by_title works fine for me if I use google_drive 1.0.1. Maybe you are using google_drive 0.3.x? google_drive 0.3.x would no longer work.

**Comment by tomay** [comment]
updating to google_drive 1.0.1 worked. Thank you.
