### ISSUE TITLE
DO I NEED TO OPEN THE URL IN THE BASH EVERYTIME AND PASTE THE CODE FROM GOOGLE?

### ISSUE THREAD

**Issue by yhjor1212** [gimite/google-drive-ruby#143]
It looks stupid when opening the page everytime by coping and pasting the code from Google. If not, please make it clear for the documentation!

**Comment by gimite** [comment]
Using GoogleDrive.saved_session may be an option:

session = GoogleDrive.saved_session

It asks you to log in via web for the first time, but it stores the credential to a file and reuse it for subsequent calls.
