### ISSUE TITLE
The Doclist API has been shut down. Please use the new Drive API

### ISSUE THREAD

**Issue by yhjor1212** [gimite/google-drive-ruby#144]
When I use session.collections and collection_by_title

Do I still expect this gem to be used well?

**Comment by tomay** [comment]
same as issue #142

**Comment by Nawshine** [comment]
Is there a new gem you recommend that supports Folders?

**Comment by gimite** [comment]
session.collection_by_title works fine for me if I use google_drive 1.0.1. Maybe you are using google_drive 0.3.x? google_drive 0.3.x would no longer work.

> Is there a new gem you recommend that supports Folders?

google_drive 1.0.1 supports folders in Google Drive API, though they are still called collections.
