### ISSUE TITLE
Export TSV

### ISSUE THREAD

**Issue by ocouronne** [gimite/google-drive-ruby#148]
TSV is not supported in v1, but exporting CSV can be complicated if there are newlines in the cells (that happens in form for example). 

You can actually export in TSV by modifying the CSV link like this:  

url = ws.csv_export_url
url = url.gsub("csv","tsv")

open(localFilename, "wb") do |f|
	f.write(session.request(:get, url, :response_type => :raw))
 	f.close 
 end

This works really well, and I would suggest that you implement a TSV export using that hack.

**Comment by gimite** [comment]
Thanks for the information. But I believe it's a kind of secret feature which is not provided by the official API. So it may stop working anytime. I would prefer not to add the hack in the library's API, and instead let people to write code like yours at their own risk.

It's also not much work to construct TSV yourself from ws.rows.
