### ISSUE TITLE
Getting columns array

### ISSUE THREAD

**Issue by vassyz** [gimite/google-drive-ruby#152]
Is there a way of getting a column as an array? Similar to the way you can get rows.

    p ws.rows  #==> [["fuga", ""], ["foo", "bar]]

**Comment by gimite** [comment]
There is no such direct method, but it's very easy to generate it from either ws.rows or ws[row, col]. e.g.,

```
p (1..ws.num_cols).map{ |c| (1..ws.num_rows).map{ |r| ws[r, c] } }
```

**Comment by vassyz** [comment]
Thank you. I'm already doing something similar, but I thought maybe I'm missing something and there's an out of the box method for getting the values.
