### ISSUE TITLE
Save method crashes sometimes, when trying to write to google sheets

### ISSUE THREAD

**Issue by shushiej** [gimite/google-drive-ruby#153]
I have a method that gets data out of a database, and pushes these values to a google spreadsheet. 
The strange thing is that sometimes it crashes when it is trying to execute the save() method (which should write the value to the sheet as I understand), and other times it writes successfully.
So what is it about the save() method that makes it crash, is there a way to mitigate this?

**Comment by gimite** [comment]
Can you give me the error message?

I heard that API requests occasionally fails with 500 etc. If that's the case, you can catch the exception and try again to workaround the error.
