### ISSUE TITLE
Missing `refresh_token` documentation

### ISSUE THREAD

**Issue by caedes** [gimite/google-drive-ruby#155]
Hello,

I just read in the [OAuth2.0 Google Developers Guides](https://developers.google.com/identity/protocols/OAuth2WebServer#refresh) that we can use some `refresh_token` to not to be force to login again and again at each script run.

Sounds awesome! :sparkles: 

Could someone provide some documentation :book: on how to use it properly with the `google-drive-ruby` :gem:? I can't make it by myself...

**Comment by gimite** [comment]
http://gimite.net/doc/google-drive-ruby/GoogleDrive.html#method-c-login_with_oauth
contains an example code to use refresh_token.

**Comment by alexvbush** [comment]
@gimite I followed the example you mentioned but I get `nil` for `refresh_token` property. Any help would be appreciated. thx.

**Comment by gimite** [comment]
I'm not really sure, but you may need to specify access_type=offline.
https://developers.google.com/identity/protocols/OAuth2WebServer#offline
contains Ruby code example.

**Comment by fuzzyjulz** [comment]
So it is possible!

If you get your first access token, then grab out the refresh token:
```
    client = Google::APIClient.new
    auth = client.authorization
    auth.client_id = "CLIENT_ID"
    auth.client_secret = "CLIENT_SECRET"
    auth.scope = [
      "https://www.googleapis.com/auth/drive",
      "https://spreadsheets.google.com/feeds/"
    ]
    auth.redirect_uri = "urn:ietf:wg:oauth:2.0:oob"
    print("1. Open this page:\n%s\n\n" % auth.authorization_uri)
    print("2. Enter the authorization code shown in the page: ")
    auth.code = $stdin.gets.chomp
    auth.fetch_access_token!
    
    print("3. This is your refresh token: %s\n\n" % auth.refresh_token)
```
This code should print out your refresh token. Now this can be reused to get a new access token every time your code runs, by using the following code to get the access token:
```
    client = Google::APIClient.new
    auth = client.authorization
    auth.client_id = "CLIENT_ID"
    auth.client_secret = "CLIENT_SECRET"
    auth.scope = [
      "https://www.googleapis.com/auth/drive",
      "https://spreadsheets.google.com/feeds/"
    ]
    auth.redirect_uri = "urn:ietf:wg:oauth:2.0:oob"
    auth.refresh_token = 'REFRESH_TOKEN'
    auth.fetch_access_token!
    auth.access_token
```
You should now see that you get a new valid access token by using `auth.access_token`

**Comment by JIAZHEN** [comment]
@fuzzyjulz following your example above however I still get `nil` as my refresh token. 
```
3. This is your refresh token: 

=> nil
```
Any idea?

**Comment by gimite** [comment]
Did you choose "Installed application" as the application type when you create the ID?

**Comment by JIAZHEN** [comment]
@gimite nope. I use `web app` when I create that credential. Really weird.

**Comment by fuzzyjulz** [comment]
I am using 'Other'

**Comment by gimite** [comment]
If you use @fuzzyjulz 's example code (i.e., setting auth.redirect_uri = "urn:ietf:wg:oauth:2.0:oob") then the application type *must* be "Installed application".

**Comment by JIAZHEN** [comment]
Fair enough. Good to clarify it. Thank you guys. At the end I just created a server to server credentials, and used `Google::Auth::ServiceAccountCredentials.new` it resolved.

**Comment by chaudhary27** [comment]
@JIAZHEN can you please guide me on how to use server to server credentials? thanks!

**Comment by JIAZHEN** [comment]
@chaudhary27 Hi, follow @fuzzyjulz 's example above but use `Google::Auth::ServiceAccountCredentials.new` to initialise the client instead of `Google::APIClient.new`, get your CLIENT ID and SECRET as a result of cresting Server to Server Credentials, it will work.

**Comment by chaudhary27** [comment]
@JIAZHEN here is what I did: credentials --> Other --> OAuth Client ID and got client_id and client_secret

```
require "google_drive"

require "rubygems"
require "google/api_client"
require "googleauth"

client = Google::Auth::ServiceAccountCredentials.new
auth = client.authorization
# Follow "Create a client ID and client secret" in
# https://developers.google.com/drive/web/auth/web-server] to get a client ID and client secret.
auth.client_id = "116400541027-c8srh2277jjsil3nk5fhvj4v97ojjkcs.apps.googleusercontent.com"
auth.client_secret = "XmRYKEIPjWj-MiFYGYje0dgm"
auth.scope =
   "https://www.googleapis.com/auth/drive " +
   "https://spreadsheets.google.com/feeds/"
auth.redirect_uri = "urn:ietf:wg:oauth:2.0:oob"
print("1. Open this page:\n%s\n\n" % auth.authorization_uri)
print("2. Enter the authorization code shown in the page: ")
auth.code = $stdin.gets.chomp
auth.fetch_access_token!
session = GoogleDrive.login_with_oauth(auth.access_token)

  # Gets list of remote files.
session.files.each do |file|
  p file.title
end
```

giving me error: 
** test.rb:9:in `<main>': undefined method `authorization' for #<Google::Auth::ServiceAccountCredentials:0x007fa1d3fb25f8> (NoMethodError)**

any ideas?

**Comment by chaudhary27** [comment]
@JIAZHEN here is what I did: Credentials --> OAuth Client ID --> got client_id and client_secret
Code:
```
require "google_drive"

require "rubygems"
require "google/api_client"
require "googleauth"

client = Google::Auth::ServiceAccountCredentials.new
auth = client.authorization
# Follow "Create a client ID and client secret" in
# https://developers.google.com/drive/web/auth/web-server] to get a client ID and client secret.
auth.client_id = "client_id"
auth.client_secret = "client_secret"
auth.scope =
   "https://www.googleapis.com/auth/drive " +
   "https://spreadsheets.google.com/feeds/"
auth.redirect_uri = "urn:ietf:wg:oauth:2.0:oob"
print("1. Open this page:\n%s\n\n" % auth.authorization_uri)
print("2. Enter the authorization code shown in the page: ")
auth.code = $stdin.gets.chomp
auth.fetch_access_token!
session = GoogleDrive.login_with_oauth(auth.access_token)

  # Gets list of remote files.
session.files.each do |file|
  p file.title
end
```

getting the error:
**test.rb:9:in `<main>': undefined method `authorization' for #<Google::Auth::ServiceAccountCredentials:0x007fa1d3fb25f8> (NoMethodError)**

any ideas? thanks!

**Comment by chaudhary27** [comment]
@JIAZHEN thanks. resolved! I had to create server to server credentials.
