### ISSUE TITLE
NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by CarlosRoque** [gimite/google-drive-ruby#156]
this is a weird error I am getting on some spreadsheets but not all

NoMethodError: undefined method `[]' for nil:NilClass
    /home/carlosr/Repos/hercules/vendor/ruby/1.9.1/gems/google_drive-1.0.0/lib/google_drive/worksheet.rb:310:in `block in save'

this code illustrates the problem

```ruby
  ws = @spreadsheet.worksheets[1]
  ws.save #for illustration purposes
  ws[1,1] = Time.strptime(time, '%m/%d/%Y %T').to_i
  ws.save
```

the first save succeeds but the second one fails
as I said, this fails on some spreadsheets but not all

any help would be greatly appreciated

**Comment by gimite** [comment]
Hm maybe the account you use don't have permission to edit the spreadsheet? Otherwise, do you have any example spreadsheet which reproduces the issue which you can share with me?

**Comment by CarlosRoque** [comment]
Thanks!
 turns out that the account only had read access

**Comment by gimite** [comment]
I see, it should show clearer error message. Thanks for the report.

**Comment by CarlosRoque** [comment]
Yes, a clearer error would have saved me some headaches. Thanks

**Comment by schuylr** [comment]
@gimite @CarlosRoque I agree with you both, I'd love to see a check for write access which throws a more helpful exception.

**Comment by gimite** [comment]
Implemented a better error message with https://github.com/gimite/google-drive-ruby/commit/1a67cd49ed85ed1a760cfcaac8d5819d215f6afe .

**Comment by CarlosRoque** [comment]
great! thank you very much
