### ISSUE TITLE
undefined method `chomp` for nil Class

### ISSUE THREAD

**Issue by chrismp** [gimite/google-drive-ruby#157]
I'm following the documentation's guide to get the access token. Here's my code so far:

```
[
	'google/api_client',
	'google_drive'
].each{|g|
	require g
}

clientId = 'MY CLIENT ID STRING'
clientSecret = 'CLIENT SECRET STRING'
client = Google::APIClient.new
auth = client.authorization
auth.client_id = clientId
auth.client_secret = clientSecret
auth.scope = [
	"https://www.googleapis.com/auth/drive.readonly",
	"https://spreadsheets.google.com/feeds/"
]
auth.redirect_uri = 'https://www.datajournalismjobs.com/oauth2callback'
auth.code = $stdin.gets.chomp
auth.fetch_access_token!
access_token = auth.access_token
```

But I get this error: `undefined method `chomp' for nil:NilClass (NoMethodError)`

How do I fix this?

**Comment by gimite** [comment]
Follow the example code in https://github.com/gimite/google-drive-ruby#how-to-use .

Assuming you are creating a command line app (not web app),

- auth.redirect_uri must be "urn:ietf:wg:oauth:2.0:oob", not 'https://www.datajournalismjobs.com/oauth2callback'

- You omitted this part of the example code, which is required. The user must open the authorization_url, get authorization code and paste it in the standard input:

```
print("1. Open this page:\n%s\n\n" % auth.authorization_uri)
print("2. Enter the authorization code shown in the page: ")
```

Also, make sure to choose "Installed app" when you create OAuth token/secret.

Alternative idea is to use:
```
session = GoogleDrive.session
```

**Comment by chrismp** [comment]
Hmm, well I'm making a site where my backend would fetch data from a Sheet. Would your code not work for what I want to do?

**Comment by gimite** [comment]
If you always want to use your own account to access Google Spreadsheet, you can still follow the example code, and perform authentication via command line on startup.

If you want to ask end users of your web app to log in to Google, and you want to access Google Spreadsheet on behalf of them, you need OAuth authentication for web app. See the first example code of:
http://gimite.net/doc/google-drive-ruby/GoogleDrive.html#method-c-login_with_oauth
Web app framework you are using, such as Rails, may have something like "Oauth2 plugin" which would make implementation easier.
