### ISSUE TITLE
Is it possible to get spreadsheets by name?

### ISSUE THREAD

**Issue by bigtunacan** [gimite/google-drive-ruby#164]
In the README.md it shows an example of retrieving an spreadsheet by key

`session.spreadsheet_by_key("pz7XtlQC-PYx-jrVMJErTcg").worksheets[0]`

Cells are being accessed by index.

Is it possible to access spreadsheets, rows, columns by name instead?  If not; how do I locate the key value?

**Comment by gimite** [comment]
For spreadsheet, you can:

    session.spreadsheet_by_title("my spreadsheet")

To access cells, you can also do:

    worksheet["A2"]

Is this what you mean by "access rows/columns by name"?

These are documented in the API doc: http://gimite.net/doc/google-drive-ruby/index.html

**Comment by bigtunacan** [comment]
@gimite Sorry for the delayed response.  Just wanted to say thanks.
