### ISSUE TITLE
Certificate verify failed

### ISSUE THREAD

**Issue by bigtunacan** [gimite/google-drive-ruby#166]
I setup the basic connection as described in the README with my client_id & client_secret.  It was all working just fine previously, now I'm getting SSL_connect failures.  Any ideas what might be causing this?

    2. Enter the authorization code shown in the page: ENTEREDMYAUTHCODEHERE
    /Users/bigtunacan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:923:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Faraday::SSLError)
      from /Users/bigtunacan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
      from /Users/bigtunacan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'
      from /Users/bigtunacan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:923:in `connect'
      from /Users/bigtunacan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
      from /Users/bigtunacan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'
      from /Users/bigtunacan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:1375:in `request'
      from /Users/bigtunacan/.rvm/gems/ruby-2.2.3@sample/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:82:in `perform_request'
      from /Users/bigtunacan/.rvm/gems/ruby-2.2.3@sample/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:40:in `block in call'
      from /Users/bigtunacan/.rvm/gems/ruby-2.2.3@sample/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
      from /Users/bigtunacan/.rvm/gems/ruby-2.2.3@sample/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:32:in `call'
      from /Users/bigtunacan/.rvm/gems/ruby-2.2.3@sample/gems/faraday-0.9.1/lib/faraday/request/url_encoded.rb:15:in `call'
      from /Users/bigtunacan/.rvm/gems/ruby-2.2.3@sample/gems/signet-0.6.1/lib/signet/oauth_2/client.rb:957:in `fetch_access_token'
      from /Users/bigtunacan/.rvm/gems/ruby-2.2.3@sample/gems/signet-0.6.1/lib/signet/oauth_2/client.rb:983:in `fetch_access_token!'
      from tmp.rb:19:in `<main>'

**Comment by gimite** [comment]
Hmm I don't know why. Can you still reproduce it?

**Comment by fitch** [comment]
I have the same problem.

**Comment by dragonsoul80** [comment]
Link below helped me fix the problem:
http://railsapps.github.io/openssl-certificate-verify-failed.html

**Comment by penguinstampede** [comment]
Getting the same Faraday error and the two fixes above did not help.  Trying to figure out the issue with ssl-doctor gave me this:

```
ruby doctor.rb accounts.google.com:443
/Users/erinkosewic/.rvm/rubies/ruby-2.0.0-p247/bin/ruby (2.0.0-p247)
OpenSSL 1.0.2d 9 Jul 2015: /usr/local/etc/openssl
SSL_CERT_DIR=""
SSL_CERT_FILE=""

HEAD https://accounts.google.com:443
OK
```
```
ruby doctor.rb CLIENTID.apps.googleusercontent.com
/Users/erinkosewic/.rvm/rubies/ruby-2.0.0-p247/bin/ruby (2.0.0-p247)
OpenSSL 1.0.2d 9 Jul 2015: /usr/local/etc/openssl
SSL_CERT_DIR=""
SSL_CERT_FILE=""

HEAD https://CLIENTID.apps.googleusercontent.com:443
OpenSSL::SSL::SSLError: hostname "CLIENTID.apps.googleusercontent.com" does not match the server certificate
```

(I used the actual client ID url instead of CLIENTID)
So it seems that the trouble is not with my install of openssl but with google's certs? Are there more certs I should install?
