### ISSUE TITLE
One file for configs and secret token

### ISSUE THREAD

**Issue by mtczerwinski** [gimite/google-drive-ruby#173]
Is it possible to save a whole sensitive information in a one file? I would like to store `CLIENT_ID`, `CLIENT_SECRET` and `TOKEN` in one file and then gem can load information for it, something like
```json
{
  "client_id": "",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://accounts.google.com/o/oauth2/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_secret": "",
  "redirect_uris": [
    "urn:ietf:wg:oauth:2.0:oob"
  ],
  "scope": [
    "https://www.googleapis.com/auth/drive ",
    "https://spreadsheets.google.com/feeds/"
  ],
  "access_token": ""
}

Are you going to introduce such functionality in future?

**Comment by gimite** [comment]
Yeah it may be a good idea. What kind of API are you thinking of?

**Comment by mtczerwinski** [comment]
I think it should allow a user to generate an empty config file.
It can use ```GoogleDrive.saved_session(File.expand_path('../../../stored_token.json', __FILE__), nil,
        client_secret['client_id'], client_secret['client_secret'])``` and save secret token in this file. Also inside script I would like to have an access to config something like: ```Config.secret_token = "dasdas"```.
When some methods from gem are invoking it checks if this file exists and if yes, then it performs functions or gem creates this file.
If there is no this file, it could generate it and show links to authorize into google service. It would be pretty easier to use this gem.

**Comment by gimite** [comment]
So are you suggesting to put client_id and client_secret inside stored_token.json? But you anyway need to specify client_id and client_secret for saved_session because it's required when stored_token.json is missing. Then what would be the benefit to store them in stored_token.json?

**Comment by mtczerwinski** [comment]
Yes exactly and I would like `saved session` to use this file. You can add methods such as `generate_config` which generate a config and user can fill this config file (client_id, client_secret) and then `saved_session` can add `token` to this file, also gem will be used data from this file. You also need to show some information about exceptions. Is it clear? Has sense?

**Comment by gimite** [comment]
Sorry for late. Sounds like a good idea. You may not need generate_config because the JSON file with client_id, client_secret would be simple enough to hand-write from scratch. Pull request with the change is welcome :)

**Comment by mtczerwinski** [comment]
Here are me modifications: https://github.com/mtczerwinski/google-drive-ruby/commits/master. Can you give me tips about your an approach for testing it?

**Comment by gimite** [comment]
Testing authentication is tricky. There are some tests under "test"
directory, but they are for operations after authentication. Manually
testing it would be fine.

Can you send me a pull request with the change? Thanks!

2015年11月21日(土) 4:31 Mateusz Czerwiński <notifications@github.com>:

**Comment by mtczerwinski** [comment]
I need do some refactors and testing but I will open PR soon :)
