### ISSUE TITLE
undefined method `bytesize' for #<GoogleDrive::Collection:0x007fca3c466500>

### ISSUE THREAD

**Issue by tomvo** [gimite/google-drive-ruby#174]
I just set-up a fresh Google Account with a fresh App (client_id/secret). I authenticated the App using the command-line request but when I afterwards want to iterate over the file collection i get a `undefined method `bytesize' for #<GoogleDrive::Collection:0x007fca3c466500>` error.

Any clue what might cause this?

This is the code:

```ruby
session = GoogleDrive.saved_session("./stored_token.json", nil, ENV['GOOGLE_DRIVE_CLIENT_ID'], ENV['GOOGLE_DRIVE_SECRET'])
# Gets list of remote files.
session.files.each do |file|
   p file.title
end

```

**Comment by gimite** [comment]
That's weird. Do you have stack trace for the error?

**Comment by tomvo** [comment]
Sorry about my late reply, I switched to the default google SDK. Which, however was a huge pain to integrate, now works well for me. Let me check if I can quickly set-up a new app to try it again.
