### ISSUE TITLE
Exception when triying to login with oauth

### ISSUE THREAD

**Issue by borlafdev** [gimite/google-drive-ruby#177]
Code that throws
`@client = Google::Auth::ServiceAccountCredentials.new(json_key_io: StringIO.new(open(@config_file).read), scope:SCOPE)
    begin
      session = GoogleDrive.login_with_oauth( @client.fetch_access_token["access_token"])
    rescue Exception => e
       debugger
    end`

Backtrace: 

/home/bdev/.rvm/gems/ruby-2.2.3/gems/google-api-client-0.8.6/lib/google/api_client/gzip.rb:14:in `initialize'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/google-api-client-0.8.6/lib/google/api_client/gzip.rb:14:in `new'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/google-api-client-0.8.6/lib/google/api_client/gzip.rb:14:in `on_complete'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/google-api-client-0.8.6/lib/google/api_client/request.rb:163:in `send'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/google-api-client-0.8.6/lib/google/api_client.rb:648:in `block (2 levels) in execute!'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/retriable-1.4.1/lib/retriable/retry.rb:27:in `perform'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/retriable-1.4.1/lib/retriable.rb:15:in `retriable'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/google-api-client-0.8.6/lib/google/api_client.rb:645:in `block in execute!'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/retriable-1.4.1/lib/retriable/retry.rb:27:in `perform'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/retriable-1.4.1/lib/retriable.rb:15:in `retriable'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/google-api-client-0.8.6/lib/google/api_client.rb:636:in `execute!'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/google-api-client-0.8.6/lib/google/api_client.rb:368:in `discovery_document'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/google-api-client-0.8.6/lib/google/api_client.rb:413:in `discovered_api'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/google_drive-1.0.4/lib/google_drive/api_client_fetcher.rb:36:in `initialize'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/google_drive-1.0.4/lib/google_drive/session.rb:77:in `new'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/google_drive-1.0.4/lib/google_drive/session.rb:77:in `initialize'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/google_drive-1.0.4/lib/google_drive.rb:79:in `new'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/google_drive-1.0.4/lib/google_drive.rb:79:in `login_with_oauth'
/home/bdev/superspider/app/models/google_reader.rb:15:in `get_dictionaries_object'
/home/bdev/superspider/app/models/filter.rb:226:in `get_dictionaries'
/home/bdev/superspider/app/models/filter.rb:236:in `dictionaries_to_brand_info'
/home/bdev/superspider/app/models/filter.rb:81:in `filter_mention'
/home/bdev/superspider/app/jobs/get_forum_blog_data.rb:25:in `block in perform'
/home/bdev/superspider/app/jobs/get_forum_blog_data.rb:17:in `each'
/home/bdev/superspider/app/jobs/get_forum_blog_data.rb:17:in `perform'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:150:in `execute_job'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/sidekiq-4.0.1/lib/sidekiq/logging.rb:30:in `with_context'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:132:in `call'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:127:in `block in process'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:166:in `stats'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:126:in `process'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:79:in `process_one'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:67:in `run'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:16:in `watchdog'
/home/bdev/.rvm/gems/ruby-2.2.3/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:24:in `block in safe_thread'

Ruby version: ruby-2.0.0-p647
OS: Linux hellaptop 4.2.0-18-generic

**Comment by gimite** [comment]
What exactly is the exception?
