### ISSUE TITLE
Unclear how to get client secret

### ISSUE THREAD

**Issue by tansaku** [gimite/google-drive-ruby#178]
Hi there,

Was trying to get set up to use your gem, however when we go to the google developer console we get a private key and not a client secret.  We get a client id in a json file like so:

```json
{
 "type": "service_account",
 "private_key_id": "dc8debf77a57fbb04bd4e25a4cb58457d16ecdef",
 "private_key": "-----BEGIN PRIVATE KEY-----<snip>\n-----END PRIVATE KEY-----\n",
 "client_email": "account-1@mechacoach.iam.gserviceaccount.com",
 "client_id": "234567654345678987",
 "auth_uri": "https://accounts.google.com/o/oauth2/auth",
 "token_uri": "https://accounts.google.com/o/oauth2/token",
 "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
 "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/account-1%40mechacoach.iam.gserviceaccount.com"
}
```

but it's unclear how we can use this with your gem.  Apologies if we are missing the obvious, but any clarification would be very welcome.

The above was created by selecting "OAuth 2.0 client IDs" from the following menu:

![](https://www.dropbox.com/s/l7v62w63oiowfjr/Screenshot%202015-12-08%2010.02.39.png?dl=1)

We don't see anywhere to select "other" as the type of application ...

**Comment by tansaku** [comment]
ah not to worry - we figured it out - found the "other:" option eventually :-)

**Comment by natetallman** [comment]
@tansaku Where did you find the "other" option? Either I'm blind to it, or it no longer exists.

**Comment by gimite** [comment]
https://gyazo.com/d699d8b7f758aec9260385e3d1bc8388
https://gyazo.com/1c9236a04e12d39a3f8078fd71859326
https://gyazo.com/fd46eda58b4581f50e6dba350709d646

You can find "Other" in the third screenshot.
