### ISSUE TITLE
How to restrict access to certain files?

### ISSUE THREAD

**Issue by zeckalpha** [gimite/google-drive-ruby#183]
I'm assuming this is at the token generation step, so it may be out of scope for this gem, but I would like to restrict a token's access to only a subset of the files in my account. Beyond creating a Google account specifically for this purpose, is there a way to do this?

**Comment by gimite** [comment]
One idea is:

- Make your app a Drive app: https://developers.google.com/drive/v3/web/install
- Ask for only https://www.googleapis.com/auth/drive.file scope (Per-file access to files created or opened by the app): https://developers.google.com/drive/v3/web/about-auth
- Install your app using your own account and open all files which you want to give permission with the app on drive.google.com .

**Comment by zeckalpha** [comment]
Thanks, I'll try that and report back.
