### ISSUE TITLE
Encoding of input values not escaping / removing bad characters (esp 0x1A)

### ISSUE THREAD

**Issue by timdiggins** [gimite/google-drive-ruby#186]
when using `Worksheet#[]=` to set values before using `Worksheet#save` you can sometimes find yourself using pathological text (e.g. stuff copied and pasted from word documents).

e.g. some text I found had 0x1A which is an  Unicode character roughly meaning 'bad data'

Now the problem with 0x1a is that it is a "valid" unicode character (of sorts) but it is invalid in XML. (see http://stackoverflow.com/a/17029396/109175)

This means that after you set some cells with `[]=` and then (some time later in your dataset traversal) you save the worksheet you get an failure from Google Drive API:

> `
GoogleDrive::Error: Update has failed: An invalid XML character (Unicode: 0x1a) was found in the value of attribute "inputValue" and element is "gs:cell".
`

It takes a long time to find out why and where this has occurred. 

Looking at the code I think that the utility function `h()` (https://github.com/gimite/google-drive-ruby/blob/08cf7938e0fc21ebc762b91db527efd7ff979ae2/lib/google_drive/util.rb#L51) is being used to escape the values going into xml (e.g. https://github.com/gimite/google-drive-ruby/blob/70b50d4924ee7f2ebe11734d881d9f3fe176a01e/lib/google_drive/worksheet.rb#L322) but it is not doing the exactly correct thing -- it is using html rather than xml escaping, and this is roughly right, but not quite, and in fact there is a difference between attribute and text escaping for xml.

What to do about 0x1A -- either h() could strip out these bad characters, or alternatively []= should raise an exception when it receives them. This way the problem would be way easier to solve. 

Would you welcome some a PR with some unit tests for h()? (or maybe replace with a ruby string encode http://stackoverflow.com/a/7573833/109175).

**Comment by gimite** [comment]
Do you know a correct way to escape "\x1a"? Or is it not acceptable in XML anyway? String#encode doesn't escape "\x1a" either:

    2.2.1 :003 > "\x1a".encode(xml: :text)
     => "\u001A"

If it's not an acceptable character, I would prefer making it an error instead of implicitly removing it. Because the user explicitly assigns "\x1a" but it is not acceptable. But I agree that we should throw an error on Worksheet#[]= instead of Worksheet#save. I'm happy to accept PR.

**Comment by timdiggins** [comment]
@gimite I think the problem with 0x1a is that it can't be escaped. It's just not a valid character (XML would not know what to do with it). And in fact Google sheets has no idea what to do with such a character. 

Anyway, I'll look into making Worksheet#[]= raise an exception on 0x1A (and perhaps other non-XML character data)
