### ISSUE TITLE
HTTPClient::KeepAliveDisconnected when saving worksheet

### ISSUE THREAD

**Issue by borlafdev** [gimite/google-drive-ruby#189]
Ruby 2.3.0
using a service account to edit another worksheet account.

After editing some values in any worksheet, calling save throws an exception:

`HTTPClient::KeepAliveDisconnected: HTTPClient::KeepAliveDisconnected: Broken pipe
	from /home/bdev/.rvm/gems/ruby-2.3.0/gems/httpclient-2.7.1/lib/httpclient/session.rb:510:in `rescue in query'
	from /home/bdev/.rvm/gems/ruby-2.3.0/gems/httpclient-2.7.1/lib/httpclient/session.rb:500:in `query'
	from /home/bdev/.rvm/gems/ruby-2.3.0/gems/httpclient-2.7.1/lib/httpclient/session.rb:170:in `query'
	from /home/bdev/.rvm/gems/ruby-2.3.0/gems/httpclient-2.7.1/lib/httpclient.rb:1238:in `do_get_block'
	from /home/bdev/.rvm/gems/ruby-2.3.0/gems/httpclient-2.7.1/lib/httpclient.rb:1021:in `block in do_request'
	from /home/bdev/.rvm/gems/ruby-2.3.0/gems/httpclient-2.7.1/lib/httpclient.rb:1134:in `rescue in protect_keep_alive_disconnected'
	from /home/bdev/.rvm/gems/ruby-2.3.0/gems/httpclient-2.7.1/lib/httpclient.rb:1128:in `protect_keep_alive_disconnected'
	from /home/bdev/.rvm/gems/ruby-2.3.0/gems/httpclient-2.7.1/lib/httpclient.rb:1016:in `do_request'
	from /home/bdev/.rvm/gems/ruby-2.3.0/gems/httpclient-2.7.1/lib/httpclient.rb:858:in `request'
	from /home/bdev/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.1/lib/faraday/adapter/httpclient.rb:33:in `call'
	from /home/bdev/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.1/lib/faraday/response.rb:8:in `call'
	from /home/bdev/.rvm/gems/ruby-2.3.0/gems/google-api-client-0.8.6/lib/google/api_client/request.rb:163:in `send'
	from /home/bdev/.rvm/gems/ruby-2.3.0/gems/google-api-client-0.8.6/lib/google/api_client.rb:648:in `block (2 levels) in execute!'
	from /home/bdev/.rvm/gems/ruby-2.3.0/gems/retriable-1.4.1/lib/retriable/retry.rb:27:in `perform'
	from /home/bdev/.rvm/gems/ruby-2.3.0/gems/retriable-1.4.1/lib/retriable.rb:15:in `retriable'
	from /home/bdev/.rvm/gems/ruby-2.3.0/gems/google-api-client-0.8.6/lib/google/api_client.rb:645:in `block in execute!'
... 12 levels...
	from /home/bdev/.rvm/gems/ruby-2.3.0/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
	from /home/bdev/.rvm/gems/ruby-2.3.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/bdev/.rvm/gems/ruby-2.3.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/bdev/.rvm/gems/ruby-2.3.0/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/bdev/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /home/bdev/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/bdev/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/bdev/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /home/bdev/trash/superspider/bin/rails:8:in `<top (required)>'
	from /home/bdev/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
	from /home/bdev/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
	from /home/bdev/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/bdev/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
	from /home/bdev/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/bdev/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'`

**Comment by gimite** [comment]
Hmm I haven't seen the error. Do you always see the error? Maybe your network connection is unstable, or Google server was unstable at that time?
