### ISSUE TITLE
Batch requests?

### ISSUE THREAD

**Issue by dsignr** [gimite/google-drive-ruby#191]
How can I make some batch requests using this gem? I know using the official gem you can do something like:
```ruby
# Fetch a bunch of files by ID
ids = ['file_id_1', 'file_id_2', 'file_id_3', 'file_id_4']
drive.batch do |drive|
  ids.each do |id|
    drive.get_file(id) do |res, err|
      # Handle response
    end
  end
end
```
Is this possible using this gem? Thank you.

**Comment by gimite** [comment]
It is currently not supported.

**Comment by dsignr** [comment]
Ok, thank you for the timely response.
