### ISSUE TITLE
Client Secret present as part of the code

### ISSUE THREAD

**Issue by ramkumar-kr** [gimite/google-drive-ruby#197]
Location - https://github.com/gimite/google-drive-ruby/blob/master/lib/google_drive.rb#L139

In Google's documentation, it says, 

> Warning: Keep your client secret private. If someone obtains your client secret, they could use it to consume your quota, incur charges against your Developers Console project, and request access to user data.

https://developers.google.com/api-client-library/ruby/guide/aaa_oauth#acquiring-client-ids-and-secrets

**Comment by gimite** [comment]
I know that it's not a recommended way, but I'm providing it for convenience to try the library.

It's a client secret with free quota, so publishing it doesn't cause serious issue, I believe.
