### ISSUE TITLE
How to change a file role type / permission?

### ISSUE THREAD

**Issue by coderaven** [gimite/google-drive-ruby#212]
I was trying to change file's role type / permission so I could make the file available to be accessed publicly:
```

require "google_drive"

session = GoogleDrive.saved_session("config.json")
file = session.file_by_title("default.csv")

if file
	file.api_file.permissions[0].type = 'anyone'
end

```
But of course, this won't work since the api_file is set to be read_only. Is there currently a way  to do this using the gem?

**Comment by gimite** [comment]
See:
http://www.rubydoc.info/gems/google_drive/GoogleDrive%2FAcl%3Apush
