### ISSUE TITLE
Migrate to Spreadsheet API v4

### ISSUE THREAD

**Issue by kapelner** [gimite/google-drive-ruby#214]
Any news on updating this to the new version? https://developers.google.com/sheets/

**Comment by gimite** [comment]
Looks nice if we switch to it. But it looks a major API change which requires significant amount of work to switch. I would work on it when I have time, but I'm happy to accept pull request for it :)

**Comment by kapelner** [comment]
Understood. Another quick question - is there any way to inject a script
<https://developers.google.com/apps-script/guides/sheets#writing_data> into
a google sheet?

On Thu, Jun 30, 2016 at 8:37 PM, Hiroshi Ichikawa <notifications@github.com>
wrote:

> Looks nice if we switch to it. But it looks a major API change which
> requires significant amount of work to switch. I would work on it when I
> have time, but I'm happy to accept pull request for it :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gimite/google-drive-ruby/issues/214#issuecomment-229826201>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAoK-Ik2Wh1ZQPe0dAvPRDkOSVq9utTGks5qRGFbgaJpZM4I-mFb>
> .
>



-- 
Adam Kapelner, Ph.D.
Assistant Professor of Mathematics
Queens College, City University of New York
65-30 Kissena Blvd., Kiely Hall Room 604
Flushing, NY, 11367 M: 516-435-6795
kapelner.com (scholar
<https://scholar.google.com/citations?user=TzgMmnoAAAAJ>|research gate
<http://www.researchgate.net/profile/Adam_Kapelner2>|publons
<https://publons.com/author/431881/adam-kapelner#profile>)

**Comment by gimite** [comment]
It looks possible with this API:
https://developers.google.com/apps-script/guides/rest/quickstart/ruby
(google_drive library doesn't support the API, but you can directly hit it, I guess.)

But it looks the API requires you to manually create the AppScript beforehand. I'm not sure if it's possible to upload AppScript via API.

**Comment by electron0zero** [comment]
any updates on this?

**Comment by gimite** [comment]
Not yet. Volunteer is welcomed :)

**Comment by shmay** [comment]
I only used this gem for basic GSheets operations, so I created a simple gem (using the v4 api) for my needs: https://github.com/shmay/google_sheets.  I plan to incrementally add more functionality.  Feature requests & PRs welcome :).

**Comment by gimite** [comment]
I pushed a pre-release of google-drive-ruby 3.0.0 which fully migrates to Sheets API v4. Try it out with:

    $ gem install google_drive --pre

See https://github.com/gimite/google-drive-ruby/blob/v3/MIGRATING.md for additional steps to upgrade your existing projects to use version 3.0.0.

**Comment by gimite** [comment]
Officially released 3.0.0.
