### ISSUE TITLE
This gem has a lot of dependencies

### ISSUE THREAD

**Issue by Fernan2** [gimite/google-drive-ruby#216]
Adding that single gem to my project has added 18 gems, as a result of dependencies, and has added 53 lines to my gemfile.lock

That makes this gem really fat and vulnerable to external issues... I wonder if all of them are worth.

**Comment by gimite** [comment]
Thanks for the report. I removed some unnecessary dependencies. But they are relatively small part of the dependencies. Remaining direct dependencies are "nokogori", "google-api-client" and "googleauth", which are essential for this gem. So it's likely that you should blame either of these 3 gems :)
