### ISSUE TITLE
Authorization for Service Accounts

### ISSUE THREAD

**Issue by Osmosis311** [gimite/google-drive-ruby#218]
Hi,

Is there any way to use the JSON file (with client ID, private_key, etc) downloaded from the API console to authenticate a session?

I'm able to successfully authenticate using the Google Ruby Library using this code:

`File.open('4b1613578679.json', 'r') do |json_io|
  @authorization = Google::Auth::DefaultCredentials.make_creds(
      scope: 'https://www.googleapis.com/auth/drive',
      json_key_io: json_io
  )
end
`

Thanks!

**Comment by gimite** [comment]
Yeah your code looks correct. After that, I believe you can create a session by:

    session = GoogleDrive.login_with_oauth(@authorization)

Alternatively, you can follow the instruction at the bottom of:
http://www.rubydoc.info/gems/google_drive/GoogleDrive.login_with_oauth
(Sorry the format is a bit broken. I will fix it.)

**Comment by gimite** [comment]
I introduced a more convenient way to use service account:

```ruby
session = GoogleDrive::Session.from_service_account_key(
    "my-service-account-xxxxxxxxxxxx.json")
```
with ver. 2.1.0.

**Comment by Osmosis311** [comment]
Thank you!!!
