### ISSUE TITLE
Uninitialized constant TestGoogleDrive::OAuth2 when running tests

### ISSUE THREAD

**Issue by BartlomiejSkwira** [gimite/google-drive-ruby#222]
I'm trying to run this gem's tests, I'm using OAuth authorization. My `account.yaml` file looks like this:
```
# Use OAuth2.
#
auth_method: "oauth2"
oauth2_client_id: "id"
oauth2_client_secret: "secret"
```

But when I fire the tests with `./test/run_test.sh` I get this:
```
Error: test_spreadsheet_online(TestGoogleDrive): NameError: uninitialized constant TestGoogleDrive::OAuth2
test/test_google_drive.rb:335:in `get_session'
test/test_google_drive.rb:21:in `test_spreadsheet_online'
     18:   @@session = nil
     19:
     20:   def test_spreadsheet_online
  => 21:     session = get_session
     22:
     23:     ss_title = "#{PREFIX}spreadsheet"
     24:     ss_copy_title = "#{PREFIX}spreadsheet-copy"
```
This points to a line in code:
```ruby
client = OAuth2::Client.new(
          account['oauth2_client_id'], account['oauth2_client_secret'],
          site: 'https://accounts.google.com',
          token_url: '/o/oauth2/token',
          authorize_url: '/o/oauth2/auth')
```

I didn't debug it further down the way.

**Comment by gimite** [comment]
Thanks for the report. It looks auth_method: "oauth2" is broken.

But anyway auth_method: "oauth2" asks you to authenticate via web browser each time, which is too annoying. I recommend you to use the default auth_method: "saved_token" instead, which still uses OAuth2, but asks you to authenticate only for the first time (and saves the token to a file).

Note that it's still recommended (and probably soon required) to specify oauth2_client_id and oauth2_client_secret even when you use auth_type: "saved_session".

I will remove auth_type: "oauth2" option and clean up account.yaml.example.

**Comment by gimite** [comment]
With https://github.com/gimite/google-drive-ruby/commit/d272a852574a41dc8e161872fa0adce89371b9f3 , I stopped using test/account.yaml, and require to put test/config.json instead. test/config.json is the same format as explained in the README.
