### ISSUE TITLE
allow_file_discovery on ACL doesn't work properly

### ISSUE THREAD

**Issue by marckohlbrugge** [gimite/google-drive-ruby#224]
When adding an ACL with `allow_file_discovery: false` it still makes the document publicly findable.

```
file = …
file.acl.push({type: "anyone", allow_file_discovery: false, role: "writer"})
```

Expected result when opening file in Google Drive:

> Anyone with the link: Anyone who has the link can access. No sign-in required.

Actual result:

> Public on the web. Anyone on the Internet can find and access. No sign-in required.

Using `with_key: true` instead of `allow_file_discovery: false` _does_ work properly.

This seems like quite a risky bug considering people might unknowingly be making their documents discoverable.

**Comment by marckohlbrugge** [comment]
Upon closer inspection it looks like `AclEntry::convert_params` [complete ignores](https://github.com/gimite/google-drive-ruby/blob/master/lib/google_drive/acl_entry.rb#L144) the `allow_file_discovery` key and only looks for `with_key` and `withLink`.

I suggest either including `allow_file_discovery` (backwards-compatible) or remove any reference to `allow_file_discovery` and force people to use one of the two supported keys instead.

**Comment by marckohlbrugge** [comment]
I tried to fix it here: https://github.com/marckohlbrugge/google-drive-ruby/commit/747062b11d8e517d14a8492b15c3dcd71ad3b9ad

I wasn't able to run the tests however as I got some runtime errors regarding `auth_method`. If someone else can run the tests and they pass, I'll create a PR.

**Comment by gimite** [comment]
Hmm I couldn't reproduce it with the HEAD version of the library. I followed your steps and it says that it's editable by "anyone with the link".

Which version of google_drive gem are you using? What if you try the same for a newly created file? Note that

    file.acl.push({type: "anyone", allow_file_discovery: false, role: "writer"})

may not work as expected if the file is already shared on the web. You should remove the corresponding ACL entry first in that case.

allow_file_discovery key should be handled in the "else" clause:
https://github.com/gimite/google-drive-ruby/blob/master/lib/google_drive/acl_entry.rb#L159

**Comment by marckohlbrugge** [comment]
Sorry, my bad. I was assuming I ran the latest version of the gem (did a regular `bundle install` with no version specified), but looks like I was running `1.0.6` anyway.
