### ISSUE TITLE
Please add a changelog

### ISSUE THREAD

**Issue by amilligan** [gimite/google-drive-ruby#226]
Or, if there is a changelog and I'm just blind, please make it more clearly available.

**Comment by gimite** [comment]
There is no changelog, unfortunately. It would be nice to have, but I'm too lazy, so I probably won't write changelog :) Sorry for inconvenience.

For major version changes, see:
https://github.com/gimite/google-drive-ruby/blob/master/MIGRATING.md

To view all changes, you can see the commit log:
https://github.com/gimite/google-drive-ruby/commits/master
and the tags for releases.
