### ISSUE TITLE
Upload file to a particular folder

### ISSUE THREAD

**Issue by Carpela** [gimite/google-drive-ruby#229]
Hi, 
Is there a way of uploading a file to a particular place by specifying a folder id. 
I think this should be possible through the underlying google API, just wondering what the syntax would be to do it here.

**Comment by Carpela** [comment]
From the google drive api. 

folder_id = '0BwwA4oUTeiV1TGRPeTVjaWRDY1E'
file_metadata = {
  name: 'photo.jpg',
  parents: [folder_id]
}
file = drive_service.create_file(file_metadata,
                                 fields: 'id',
                                 upload_source: 'files/photo.jpg',
                                 content_type: 'image/jpeg')
puts "File Id: #{file.id}"

I'm assuming you're using that service to upload the initial file. Just need that parent parameter. 
I'll have a look and see if it's straightforward enough to add it to a parameter without breaking anything.

**Comment by Carpela** [comment]
Had a look through the code. 
One of those ones that I'm not sure if it's by design. 
Every time you're hitting it, in various different places 
e.g. session#upload_from_file, session#upload_from_io
you're calling a self.id for the parents parameter. 
Now, we could overwrite that with the id if a params[:folder_id] exists to allow you to upload to anywhere without needing to navigate to the appropriate folder first (which sometimes can be a pain, from memory). 
But that would require a lot of changes in a lot of different places which might break stuff. 
Happy to take a look, but without knowing where else you're using it, am wary of wasting time on something that will just break everything.

**Comment by Carpela** [comment]
Sorry, doing a bit of a stream of consciousness investigation here...
I think that if you throw a {parents:<folder_id>} into the upload_from_file method from either session or collection it should work, but doesn't. Just uploads to the top level file. 
e.g.
    
    session.upload_from_file(file_path, file_name, {convert:false, parents:folder_id}) 

uploads the file but dumps it at the top level. 

It turns out this is beacuse I'm using v1.06...

**Comment by gimite** [comment]
Yeah, you can use GoogleDrive::Collection#upload_from_file, or passing :parents parameter to GoogleDrive::Session#upload_from_file as you pointed out, but both require google_drive v2.0.2 or later (I guess). Did it solve the issue?

**Comment by Carpela** [comment]
Yep. that did the trick. 
Incidetnally, a session.collection_by_id(id) method would be really handy. It appears to be what you're doing anyway with session.collection_by_url...

**Comment by gimite** [comment]
You can use session.file_by_id(id). It also returns a collection. I agree that it would be better to have session.clllection_by_id as well for consistency.

**Comment by Harshalzzzzzzz** [comment]
@gimite session.upload_from_file( "path/to/file.csv","file.csv",convert: false) leads to this error:


ArgumentError in Form::FormsController#google_spreadsheet
unknown keyword: supports_all_drives
