### ISSUE TITLE
Use without hardcoding api keys?

### ISSUE THREAD

**Issue by RBIII** [gimite/google-drive-ruby#230]
Is there a way I can use this gem without having to hard code my google api key(s) in json files?

**Comment by gimite** [comment]
If you mean OAuth client token/secret by "API key", then the answer is "no". OAuth is required to use this gem. You can store them in other storage (e.g., database) and provide them directly, but you need to store them somewhere. See
https://github.com/gimite/google-drive-ruby/blob/master/doc/authorization.md
for different options for authorization.

**Comment by LaurentKretz** [comment]
Hi gimite, 

I guess RBIII meant how to use the GoogleDrive::Session.from_service_account_key() without a file_path but a Json.parse(ENV['GOOGLE_SECRET']). 

I have the same problem here, I'd like to store my service account key as a variable in order not to have to send upload it on github. Any way to make this below work ? 

session = GoogleDrive::Session.from_service_account_key(JSON.parse(ENV['GOOGLEDRIVE_SECRET'])) 

Many thanks in advance !

**Comment by gimite** [comment]
As documented here:
http://www.rubydoc.info/gems/google_drive/2.1.1/GoogleDrive/Session#from_service_account_key-class_method

You can provide either a file path or an IO object. So you can do it by e.g.:
```ruby
session = GoogleDrive::Session.from_service_account_key(StringIO.new(ENV['GOOGLEDRIVE_SECRET']))
```

BTW If your goal is just not to upload it to Github, you can keep using a JSON file but just not add it to Git.

**Comment by pezholio** [comment]
Another option is Base64 encoding the contents of your JSON file and storing that as an API key. This is the approach I use when hosting my app on Heroku and storing my source code in a public GitHub repo. I have the `client_secret.json` file stored locally and `.gitignore`d 

For example (in a Rails initializer):

```
client_secret = if ENV['GDRIVE_AUTH']
  StringIO.new(Base64.decode64(ENV['GDRIVE_AUTH']))
else
  'client_secret.json'
end

$google_drive_session = GoogleDrive::Session.from_service_account_key(client_secret)
```

**Comment by maxkopych** [comment]
GoogleDrive::Session.from_config also accept object so you can do

```
GoogleDrive::Session.from_config(OpenStruct.new({
                                                      client_id: ENV['GDRIVE_CLIENT_ID'],
                                                      client_secret: ENV['GDRIVE_CLIENT_SECRET'],
                                                      scope: ["https://www.googleapis.com/auth/drive", "https://spreadsheets.google.com/feeds/"],
                                                      refresh_token: ENV['GDRIVE_REFRESH_TOKEN']
                                                    }))
```
