### ISSUE TITLE
Get new data after changes in spreadsheet 

### ISSUE THREAD

**Issue by miguelcarvajal** [gimite/google-drive-ruby#236]
I have installed the gem in a telegram bot. It works perfectly. But I haven't figure it out how to reload the new data from spreadsheet after changing it in Google Drive. 

This is what I have so far:

```
session = GoogleDrive::Session.from_config("config.json")

ws = session.spreadsheet_by_key("----------").worksheets[0]

@titular = ws[3,3]
@autor = ws[2,1]
@enlace = ws[3,4]

ws.reload

```
And then I call the data:

```
when /autor/i
      content = @autor
      bot.api.send_message(chat_id: message.chat.id, text: content)

```    

But it is still getting the old data from row even after changing it in the remote spreadsheet.

In order to pull the new data I have to restart the bot. 

Do you know a better way to resolve this?

Thanks!

**Comment by gimite** [comment]
You need to run:
```ruby
@titular = ws[3,3]
@autor = ws[2,1]
@enlace = ws[3,4]
```
again after ```ws.reload```. Looking at the code, it looks you are currently assigning to these fields only before you reload.

**Comment by miguelcarvajal** [comment]
Thank you! Yes, it's the way to go. It's working.
