### ISSUE TITLE
`Session.from_config` accepting only file or `Config` object, but I want to just pass only necessary arguments

### ISSUE THREAD

**Issue by kibitan** [gimite/google-drive-ruby#247]
it looks `Session.from_config` is accepting file path or `Config` object by comment below.

https://github.com/gimite/google-drive-ruby/blob/master/lib/google_drive/session.rb#L86-L93
```
    # You can also provide a config object that must respond to:
    #   client_id
    #   client_secret
    #   refesh_token
    #   refresh_token=
    #   scope
    #   scope=
    #   save
```

but I think its not extendable of passing new `Config` object, its really tight coupling with internal API. 
how do you think define `Session.from_config_args(client_id:, client_secret:, refresh_token:, scope: DEFAULT_SCOPE)` ?

**Comment by gimite** [comment]
Thanks for the suggestion.

Well, if you already have a refresh_token, it's not so hard to create a session anyway:

```ruby
      credentials = Google::Auth::UserRefreshCredentials.new(
        client_id: client_id,
        client_secret: client_secret,
        scope: scope,
        redirect_uri: 'urn:ietf:wg:oauth:2.0:oob',
        refresh_token: refresh_token)
      credentials.fetch_access_token!
      session = Session.from_credentials(credentials)
```

So I don't see a strong need of a new method. I believe the main benefit of Session.from_config is that it performs interactive authorization (by redirecting you to an URL) and reuse the credential later.

**Comment by kibitan** [comment]
@gimite oh wow! i don't  know your suggesting way, yea its exactly what i want to do. is it documented? if it works well, so  i totally agree with your opinion.

**Comment by gimite** [comment]
> Is it documented?

Well, kind of. Session#from_credentials is documented here:
http://www.rubydoc.info/gems/google_drive/2.1.2/GoogleDrive/Session#from_credentials-class_method

And other than that, it's a standard code to construct a UserRefreshCredentials instance from a refresh token. You can also refer to the third code snippet of:
https://github.com/gimite/google-drive-ruby/blob/master/doc/authorization.md#on-behalf-of-the-user-who-accesses-your-web-app-web-based-authorization
as an example.

But it may be better to document this exact case somewhere.

**Comment by kibitan** [comment]
@gimite thank you for your kindly reply 😄
