### ISSUE TITLE
Is it possible to "protect" some cells ?

### ISSUE THREAD

**Issue by waruboy** [gimite/google-drive-ruby#250]
First, thank you for the gem. We use it at storemapper.co and are very happy with it.

Some issue that we have is our users keep changing their header row, that we depended on to do some sync with our app. Is there anyway to protect this cells from edit via gem?

https://developers.google.com/sheets/api/samples/ranges

**Comment by gimite** [comment]
You can definitely do it manually on the Google Spreadsheet web interface. So far you cannot do that programatically with google_drive library. The only way to do that programatically is to hit the API you mentioned by yourself. google_drive library still uses the previous version of Spreadsheet API (v3), and we first need to switch to v4 API to implement it.

**Comment by waruboy** [comment]
Thanks for responding. Yes, that is what I thought. We need to do it programmatically though so perhaps we should roll out our own library. Once again thanks for your work on the gem!

**Comment by gimite** [comment]
NP. FYI google-api-client library should make it easy to hit the V4 API.
