### ISSUE TITLE
How do I store/re-use session without having to create a new session before the old one expired?

### ISSUE THREAD

**Issue by feliperaul** [gimite/google-drive-ruby#251]
Im trying my best to understand how to use this gem properly.

As far as I understand, after I use `credentials.fetch_access_token!` and `session = GoogleDrive::Session.from_credentials(credentials)`, I have a new `GoogleDrive::Session` instance saved in `session` that I can use to issue commands.

I managed to test some commands and they work. I can open and edit spreadsheets trough that session instance. 

The issue is: obviously, as soon as my rails action run, that instance of `GoogleDrive::Session` is going to be garbaged collected. 

It can't be that I must iniciate the credentials process all over since I just received a token with 1 hour expiration, right? But how to persist that instance of GoogleDrive::Session for 1 hour or how to re-use that token?

I tried saving the return of `credentials.fetch_access_token!` in the database and then using `GoogleDrive::Session.from_credentials(user.last_token)` but it doesnt work and returns `dailyLimitExceededUnreg` errors.

**Comment by gimite** [comment]
See the last paragraph starting with "The session above expires in 1 hour." in this section of the doc:

https://github.com/gimite/google-drive-ruby/blob/master/doc/authorization.md#on-behalf-of-the-user-who-accesses-your-web-app-web-based-authorization

**Comment by feliperaul** [comment]
@gimite Yes I read that but I thought it could be simpler/faster because it involves making a new auth request anyways. 

In my tests, if I save the return hash from the `fetch_access_token!` method, I can use something like `session = GoogleDrive::Session.from_access_token(current_user.google_docs_current_token["access_token"])` and it works without having to make a new request.

Of course I'm also having to save the timestamp for the expiration of the token to see if I still can use this token. 

Is this not recommended?

**Comment by gimite** [comment]
Yeah that would be more efficient if you often reuse the session again in 1 hour. Anyway looks like you have already solved the issue? Any remaining issues?

**Comment by feliperaul** [comment]
Nope just wanted to get your feedback if there would be any drawbacks. Thanks @gimite
