### ISSUE TITLE
accessing folders as well as files

### ISSUE THREAD

**Issue by BKSpurgeon** [gimite/google-drive-ruby#255]
Hi there

thank you for writing this gem. i am sure a lot of people appreciate it.

Is there a way of accessing folders with this gem?

any assistance much appreciated.

rgds

Ben

**Comment by gimite** [comment]
Yes. e.g., Use Session#collection_by_title method:
http://www.rubydoc.info/gems/google_drive/GoogleDrive/Session#collection_by_title-instance_method

See the document of Session class for other methods:
http://www.rubydoc.info/gems/google_drive/GoogleDrive/Session

**Comment by BKSpurgeon** [comment]
Thank you sir - this is very nice library.

I have a few further questions:

(1) sometimes i perform multiple actions on the save drive instance. for example, i might get 3 files from google drive instance. I"ll then make some changes in google drive (add files/ remove them). when I ask that same drive instances to get the files again - it still returns how google drive looked before i made those changes. any advice here?

(2) how/where did you learn the Google drive API in order to write this gem? and how/where can i learn to get to the position where i can contribute as well?

advice much appreciated.

rgds

Ben

**Comment by gimite** [comment]
> (1) sometimes i perform multiple actions on the save drive instance. for example, i might get 3 files from google drive instance. I"ll then make some changes in google drive (add files/ remove them). when I ask that same drive instances to get the files again - it still returns how google drive looked before i made those changes. any advice here?

Did you get the files again immediately after you made the change, or a while later? Which method did you use to get the list of files? Was that change applied if you check drive.google.com? I haven't confirmed, but it may take some time before the change takes effect.

> (2) how/where did you learn the Google drive API in order to write this gem? and how/where can i learn to get to the position where i can contribute as well?

I learned mostly from the official documentation:
https://developers.google.com/drive/v3/web/about-sdk
It doesn't mention much about the Ruby library, so I also needed googling to find samples.

If you find any issues with the library, it would be great if you read the code of google-drive-ruby and also the API doc above to identify the issue, and send pull requests.

**Comment by BKSpurgeon** [comment]
> Did you get the files again immediately after you made the change, or a while later? Which method did you use to get the list of files? Was that change applied if you check drive.google.com? I haven't confirmed, but it may take some time before the change takes effect.

Thank you sir - it turned out it was a bug in my code. But it does raise a very interesting question: what about transactions by which things can be written/unwritten and the changes affected only after committing?

I am very slowly learning the API it's quite interesting.

**Comment by gimite** [comment]
> what about transactions by which things can be written/unwritten and the changes affected only after committing?

I don't think Google Drive API has a concept of transaction, but I may be wrong. There's a way to batch multiple requests:
https://developers.google.com/drive/v3/web/batch
(which google-drive-ruby doesn't support now) But I believe it doesn't form a transaction.

Anyway there are many methods which are not implemented in google-drive-ruby e.g., the batch request above. Pull requests to add those would be appreciated.
