### ISSUE TITLE
Team Drive support

### ISSUE THREAD

**Issue by llange** [gimite/google-drive-ruby#259]
Google introduced at the end of last year [Team Drive](https://gsuite.google.com/learning-center/products/drive/get-started-team-drive/), which is a specific drive for enterprise customers (more specifically G Suite Enterprise, G Suite Business, or G Suite for Education editions.).

google-api-ruby-client support Team Drives since a few versions, but I couldn't have google-drive-ruby open a document hosted on a Team Drive. It fails with the following error:
```
google-api-client-0.11.2/lib/google/apis/core/http_command.rb:218:in `check_status': notFound: File not found: xxxxxxxxxxxxxxxxxxx. (Google::Apis::ClientError)
```

The method called was
```
session.spreadsheet_by_key(spreadsheet)
```

which at some point calls google-drive-ruby's method:
```
file_by_id
```
in google_drive-2.1.3/lib/google_drive/session.rb:216

To make it open the file, I had to patch that function from
```
    def file_by_id(id)
      api_file = self.drive.get_file(id, fields: '*')
      wrap_api_file(api_file)
    end
```
to
```
    def file_by_id(id)
      api_file = self.drive.get_file(id, fields: '*', supports_team_drives: true)
      wrap_api_file(api_file)
    end
```

And that was all that was necessary to open the file for reading.

I have not tested the "write" part as it is not in my use-case for the moment.

**Comment by gimite** [comment]
Thanks for the report. Looks like we should just add that parameter. I will do that.

**Comment by gimite** [comment]
Supported with gem 2.1.4.
