### ISSUE TITLE
Number of files retrieved limited to 100

### ISSUE THREAD

**Issue by fuzzyjulz** [gimite/google-drive-ruby#261]
I'm doing the following:
GoogleDrive.login_with_oauth(access_token).collection_by_url(url).files

It looks to me that we are only getting 100 files in this location, and it appears that it is coming from google like that, as it seems to be paginated.

I can see that there is a next page token in the result set:

 @incomplete_search=false,
 @kind="drive#fileList",
 @next_page_token=
  "V1*3|0|xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">

I can have a look into it, but it seems like a bug to me, I can't see any other way to get the next set of results

**Comment by gimite** [comment]
See the document:
http://www.rubydoc.info/gems/google_drive/GoogleDrive/Collection#files-instance_method

> By default, it returns the first 100 files. See document of GoogleDrive::Session#files method for how to get all files.

So you can use a block parameter to get all files:

```ruby
GoogleDrive.login_with_oauth(access_token).collection_by_url(url).files do |file|
  p file
end
```

This is unfortunately by design for backward compatibility.

**Comment by fuzzyjulz** [comment]
Awesome! That seems to work!
