### ISSUE TITLE
Spreadsheet by path ?

### ISSUE THREAD

**Issue by c0ze** [gimite/google-drive-ruby#262]
When I have two files with the same name, how do I get a specific file ?

For example, I have two files named 2016, under `/foo` and `/bar` folders respectively.

If I call spreadsheet_by_title "2016", I always get `/bar/2016` . is there a way to get `/foo/2016` ?

**Comment by gimite** [comment]
You can use:
```ruby
session.file_by_title(["foo", "2016"])
```

"File" in this library includes spreadsheet, and file_by_title accepts an Array to specify the path. So it should work.

Note that a file name, or even a path, is not unique in Google Drive. It allows multiple files with the same path. So the above may still not identify a single file. If you want a way to always identify a single file, you  must use an ID like file_by_id method.

**Comment by c0ze** [comment]
Thank you ! This is helpful.
