### ISSUE TITLE
Append to pre-existing worksheet?

### ISSUE THREAD

**Issue by VirenMohindra** [gimite/google-drive-ruby#263]
How can we append to a pre-existing worksheet? The only workaround I've found is incrementing but this doesn't solve the issue of overwritten data when I restart the script

```
                    while true do
                    row = $row_inc
                    ws.insert_rows[row, 1] = variable_1
                    ws.insert_rows[row, 2] = variable_2
                    ws.insert_rows[row, 3] = variable_3
                    ws.insert_rows[row, 4] = variable_4
                    $row_inc += 1
```

Is there any workaround?

Thanks

**Comment by gimite** [comment]
You can use Worksheet#num_rows. e.g.:

```ruby
r = ws.num_rows + 1
ws[r, 1] = "hoge"
ws[r, 2] = "foo"
ws[r, 3] = "bar"
```

Or:

```ruby
ws.update_rows(ws.num_rows + 1, 1, [["hoge", "foo", "bar"]])
```

It may be better if it has a method called add_rows() or something...

**Comment by VirenMohindra** [comment]
The first code snippet worked perfectly thank you so much!
