### ISSUE TITLE
Google::Apis::ClientError: Invalid request

### ISSUE THREAD

**Issue by monkeysuffrage** [gimite/google-drive-ruby#265]
I'm seeing this error:

2.3.1 (main):0 > file = session.file_by_title("sample spreadsheet")
=> #<GoogleDrive::Spreadsheet id="1gNAjTl1D7exEkKL-Wzvsb7GhyANes1M1iwo6xi6_J6k" title="sample spreadsheet">
2.3.1 (main):0 > file.download_to_file("sample spreadsheet")
Google::Apis::ClientError: Invalid request
from C:/Ruby23/lib/ruby/gems/2.3.0/gems/google-api-client-0.12.0/lib/google/apis/core/http_command.rb:218:in `check_status'

This is with:
googleauth-0.5.1, google-api-client-0.12.0

Should I be using older libraries?

**Comment by gimite** [comment]
Spreadsheets support "export", but not "download". So it should be like this:

```ruby
file = session.file_by_title("sample spreadsheet")
file.export_as_file("sample.csv")
```

Note that the file name also must have one of the supported extensions like .csv.

The error message for download is too cryptic, though. It should be improved...

**Comment by monkeysuffrage** [comment]
Great!
That's working for me now. So what would the corresponding `update_from_file` be for spreadsheets?
I just want to be able to sync my local files with Google Sheets.

**Comment by gimite** [comment]
Looks like update_from_file works fine for spreadsheets too, with .csv file, for example. But it resets formats etc. of the spreadsheet, just like you re-upload the sheet.

You need to use methods of ss.worksheets[0] to update each cell if you want to update the contents keeping the format.
