### ISSUE TITLE
Authenticating on Heroku: command line authorization

### ISSUE THREAD

**Issue by Lemez** [gimite/google-drive-ruby#266]
Hello,
The gem works perfectly on my local machine using the `from_config` method where I can use the command line to authenticate the first time the app runs.

Am having difficulty understanding how to authenticate in production on Heroku, when I am not able to access the command line for manual input, and the authentication fails silently.

I know this has been referenced in [#172](https://github.com/gimite/google-drive-ruby/issues/172), but the solution there isn't working for me. My code:

`$session = GoogleDrive.saved_session(config = ENV['HOME'] + "./stored_token.json", proxy=nil, client_id=ENV["CLIENT_ID"], client_secret=ENV["CLIENT_SECRET"]) `

results in the same output in Heroku logs 

`2. Enter the authorization code shown in the page: 2017-07-05 04:24:11 - NoMethodError - undefined method 'chomp' for nil:NilClass:`

as `$session = GoogleDrive::Session.from_config("client.json")`

Having searched through all the docs, and read every issue, it's time to reach out to the creators!

Thanks.

**Comment by gimite** [comment]
Sounds good to use the service account in your case.

Thanks for the feedback. I added a note in the first paragraph of:
https://github.com/gimite/google-drive-ruby/blob/master/doc/authorization.md
