### ISSUE TITLE
Surpressing Logs

### ISSUE THREAD

**Issue by waruboy** [gimite/google-drive-ruby#269]
This gem usage produce significant volume of logs., for example when loading worksheet. Is there any way to reduce them?

**Comment by waruboy** [comment]
I think most of the logs are originated by the google-api-client gem, but perhaps you have any thought on this?

**Comment by gimite** [comment]
See https://github.com/gimite/google-drive-ruby/issues/215#issuecomment-311729233

**Comment by waruboy** [comment]
@gimite thanks!
