### ISSUE TITLE
Update has failed: An invalid XML character (Unicode: 0x13)

### ISSUE THREAD

**Issue by tscung** [gimite/google-drive-ruby#270]
Update has failed: An invalid XML character (Unicode: 0x13) was found in the value of attribute "inputValue" and element is "gs:cell".

**Comment by gimite** [comment]
This is similar to #186. As the error message says, you put a string containing "\x13" which is invalid in XML (thus in Google Spreadsheet API). Remove the character if it's needless. We should do something similar to #188 for this character too.
