### ISSUE TITLE
Google::Spreedsheet  update_from_file  is throwing Server error - 500 (Some times)

### ISSUE THREAD

**Issue by SarathPendlimarri** [gimite/google-drive-ruby#271]
Hi ,

From few days i am frequently facing 500 server error while we are updating Google Spreedsheet with the help of update_from_file method .We are trying to update nearly **4 MB** of File with **14000 records**.

**Error Details :**
1. Error Message : Server Error
2. Error Code : 500

**Please find my Backtrace below :**

`[2017-07-31 20:16:56 +0530] [12220] ERROR:   C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/google-api-client-0.9.24/lib/google/apis/core/http_command.rb:215:in `check_status'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/google-api-client-0.9.24/lib/google/apis/core/api_command.rb:104:in `check_status'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/google-api-client-0.9.24/lib/google/apis/core/http_command.rb:179:in `process_response'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/google-api-client-0.9.24/lib/google/apis/core/http_command.rb:287:in `execute_once'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/google-api-client-0.9.24/lib/google/apis/core/http_command.rb:107:in `block (2 levels) in execute'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/google-api-client-0.9.24/lib/google/apis/core/http_command.rb:104:in `block in execute'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/google-api-client-0.9.24/lib/google/apis/core/http_command.rb:96:in `execute'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/google-api-client-0.9.24/lib/google/apis/core/base_service.rb:351:in `execute_or_queue_command'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/google-api-client-0.9.24/generated/google/apis/drive_v3/service.rb:772:in `get_file'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/google_drive-2.1.2/lib/google_drive/session.rb:216:in `file_by_id'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/google_drive-2.1.2/lib/google_drive/session.rb:257:in `spreadsheet_by_key'
D:/Tableau/Tableau_Work/P-161/RUBY_Code/bi/lib/google/spreadsheet.rb:19:in `read'
D:/Tableau/Tableau_Work/P-161/RUBY_Code/bi/lib/reports/spreadsheet.rb:63:in `load_spreadsheet'
D:/Tableau/Tableau_Work/P-161/RUBY_Code/bi/lib/reports/spreadsheet.rb:26:in `initialize'
D:/Tableau/Tableau_Work/P-161/RUBY_Code/bi/lib/reports/base/report.rb:178:in `new'
D:/Tableau/Tableau_Work/P-161/RUBY_Code/bi/lib/reports/base/report.rb:178:in `report'
D:/Tableau/Tableau_Work/P-161/RUBY_Code/bi/lib/reports/base/report.rb:66:in `block in run'
D:/Tableau/Tableau_Work/P-161/RUBY_Code/bi/lib/reports/base/report.rb:62:in `times'
D:/Tableau/Tableau_Work/P-161/RUBY_Code/bi/lib/reports/base/report.rb:62:in `each'
D:/Tableau/Tableau_Work/P-161/RUBY_Code/bi/lib/reports/base/report.rb:62:in `run'
D:/Tableau/Tableau_Work/P-161/RUBY_Code/bi/lib/reports/margin/aggregate.rb:107:in `run'
D:/Tableau/Tableau_Work/P-161/RUBY_Code/bi/lib/tasks/reports.rb:21:in `block (3 levels) in <top (required)>'
D:/Tableau/Tableau_Work/P-161/RUBY_Code/bi/lib/logger.rb:66:in `task'
D:/Tableau/Tableau_Work/P-161/RUBY_Code/bi/lib/tasks/reports.rb:18:in `block (2 levels) in <top (required)>'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
C:/Ruby23-x64/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
C:/Ruby23-x64/bin/rake:22:in `load'
C:/Ruby23-x64/bin/rake:22:in `<main>'`

**Comment by gimite** [comment]
Yeah it is known that Google Drive API sometimes returns 500. Catch exception and retry yourself. It may be nice if the library provides an option to retry automatically...
