### ISSUE TITLE
download_to_file downloads file but returns nil

### ISSUE THREAD

**Issue by jen-v** [gimite/google-drive-ruby#275]
Hi,
I have the following code:

```
    def download
      found = google_files.select { |f| f.id == file_id }
      file_title = found.first.title
      file = session.file_by_title(file_title)
      path = File.join(Backup.base_directory, file_title)
      file.download_to_file("#{path}")
    end
```

When I execute it, the console outputs `Success - nil` but the file is created in the correct folder. 
I want to work with this downloaded object but I cannot refer to it because it's `nil`. Is this an expected behavior?

```
[...]
Writing chunk (1397 bytes)
Writing chunk (1397 bytes)
Writing chunk (1397 bytes)
Writing chunk (619 bytes)
Success - nil

=> nil
[4] pry(main)>
```

**Comment by gimite** [comment]
Yes, that's the intended behavior. download_file just downloads to the given path.

You can use download_to_string if you want to get the content as a String instead:
```ruby
s = file.download_to_string
```
Or you can open the downloaded file and do whatever you want:
```ruby
file.download_to_file(path)
open(path) do |f|
  ...
end
```
