### ISSUE TITLE
google-api-client 13.0+

### ISSUE THREAD

**Issue by janmisar** [gimite/google-drive-ruby#276]
I use `google_drive` as a part of fastlane script and latest fastlane version requires

`'google-api-client', '>= 0.13.1', '< 0.14.0'`

It would be great to support latest `google-api-client` version.

**Comment by gimite** [comment]
Thanks for the request. Done with google_drive 2.1.6.

**Comment by janmisar** [comment]
Awesome! Thank you! 👍

**Comment by chamnap** [comment]
@gimite, can we bump the google-api-client to the latest `0.19.8` again?

**Comment by gimite** [comment]
Done. Thanks for the report.
