### ISSUE TITLE
API not fetching more than 100 files

### ISSUE THREAD

**Issue by Lemez** [gimite/google-drive-ruby#277]
Hi there,
Is there a maximum number of files that can be retrieved? I am storing images in a folder "DB" with a child folder "Select" inside that. I send the data as json to an Angular front end.

 When I add an image to one folder, the number of files retrieved goes down by one in the other folder, to a maximum of 99/100 combined.

Am I missing something in the settings?

Thanks

**Comment by gimite** [comment]
See #261.
