### ISSUE TITLE
issue with files being auto-converted to docs

### ISSUE THREAD

**Issue by nickyromeijn** [gimite/google-drive-ruby#283]
Hello,

Im using this gem with a google drive service account and while uploading files works perfectly i'm having an issue where .png files are automatically converted to google docs documents. The issue with this is that i'm unable to retrieve them when they get converted. If i use the  download_to_string or download_to_file method i always get an invalid request error when used on converted files. 

I can't seem to get the export_to_file or export_to_string method working either when i supply "image/png" to as format i get another invalid request error. 

Is there way to supply a config that disables the auto conversion of png files into docs or a way to convert them back to images using the gem?

**Comment by gimite** [comment]
Yes. Specify :convert => false as written in the doc:
```ruby
session.upload_from_file("/path/to/hoge.txt", "Hoge", :convert => false)
```
http://www.rubydoc.info/gems/google_drive/GoogleDrive/Session#upload_from_file-instance_method
