### ISSUE TITLE
How can I get the last modified date of a file ?

### ISSUE THREAD

**Issue by CreeperLava** [gimite/google-drive-ruby#284]
Currently, reading a few cells from a large spreadsheet is extremely slow, probably because the API downloads the entire file each time. I would like to know if I can save the sheet locally and verify if there have been any recent changes, to avoid having to redownload it entirely.

Also, is there a way to download google sheet files, or are they only available through the sheet API ? I suppose I can convert them that way, it's just less practical.

Below the code I am using, for reference.
```
require 'google_drive'
require 'fileutils'

session = GoogleDrive::Session.from_service_account_key("My Project-9b0747d0a01b.json")

ws = session.spreadsheet_by_key("1Gvnz_trNOUgW6CSI3eeEYk7SvqsSklIgVuoHDlmw8e8").worksheets[1]
p ws[1, 1]
```

In any case, thanks for your work. I couldn't get the official google API to work, and it's a lot more complicated than yours.

**Comment by gimite** [comment]
I haven't tested but it should be available as:
```ruby
ss = session.spreadsheet_by_key("1Gvnz_trNOUgW6CSI3eeEYk7SvqsSklIgVuoHDlmw8e8")
p ss.modified_time
```

As documented here:
http://www.rubydoc.info/gems/google_drive/GoogleDrive/File
> In addition to the methods below, properties defined here are also available as attributes: developers.google.com/drive/v3/reference/files#resource

> Also, is there a way to download google sheet files, or are they only available through the sheet API ?

You can use export_as_file (or other export_*) method to export either the whole sheet or a specific worksheet as CSV etc.:
http://www.rubydoc.info/gems/google_drive/GoogleDrive/File#export_as_file-instance_method
http://www.rubydoc.info/gems/google_drive/GoogleDrive/Worksheet#export_as_file-instance_method

**Comment by CreeperLava** [comment]
Thank you very much. That doc is definitely going to be useful.

**Comment by gimite** [comment]
Sorry it looks I forgot to reply this.

> It doesn't look like the "modified_time" function is described in the doc.

It **is** documented indirectly here (I agree that it's a bit hard to notice):

> In addition to the methods below, properties defined here are also available as attributes: developers.google.com/drive/v3/reference/files#resource

> "session.spreadsheet_by_key" doesn't just pull the metadata, it pulls the entire spreadsheet with it ?

It does just pull the metadata, I believe. The actual contents are loaded only when you access |worksheets| property.

**Comment by CreeperLava** [comment]
I see, that's really useful information, thank you (a bit late, but appreciated nonetheless^^).
