### ISSUE TITLE
How can I create a spread sheet using this gem?

### ISSUE THREAD

**Issue by staycreativedesign** [gimite/google-drive-ruby#286]
Mayb im not seeing it in the API but how would I create a spreadsheet?

**Comment by gimite** [comment]
Use this one:
http://www.rubydoc.info/gems/google_drive/GoogleDrive/Session#create_spreadsheet-instance_method

**Comment by staycreativedesign** [comment]
Are you kidding me, ARGH I was looking somewhere else!!!!! Thank you
