### ISSUE TITLE
How to test spreadsheets?

### ISSUE THREAD

**Issue by Envek** [gimite/google-drive-ruby#289]
Hello!

How can I test that my app writes correct data to the spreadsheet? Is there a way to create spreadsheet stub (without connectin to real Google Apps) and read-write data to it?

I can see in sources that I can create dummy session but that is all. If I try to create spreadsheet from it I will get an error:

```ruby
session = GoogleDrive::Session.new_dummy
session.spreadsheet_by_url("https://docs.google.com/spreadsheets/d/some-fake-key").worksheets[0]
# NoMethodError: undefined method `drive' for nil:NilClass
# from …/google_drive-2.1.7/lib/google_drive/session.rb:163:in `drive'
```

**Comment by gimite** [comment]
No, currently there is no support for it, unfortunately. Though you can write your own stub of GoogleDrive::Session etc. to test your app. Pull request with any helper class for tests is appreciated :)

google_drive library itself is also tested with a real connection to Google Drive.
