### ISSUE TITLE
Export file in pdf/doc/text format

### ISSUE THREAD

**Issue by antonovga** [gimite/google-drive-ruby#29]
Tried to download file with format that differs from upload.
(from readme)
file = session.file_by_title("hello.html")
file.download_to_file("/path/to/hello.pdf")

As result, dowanloaded file with html inside.

As I understand from google api docs I need to form the url like this
https://docs.google.com/feeds/download/documents/Export?docID=id_from_hello_html&exportFormat=pdf&format=pdf

How can I apply(or pass) theese paramenters to dowload method?

**Comment by gimite** [comment]
It was fixed in google_drive 1.0.0. I confirmed that Google Document -> .pdf and .docx works.
