### ISSUE TITLE
Upload file to specific folder.

### ISSUE THREAD

**Issue by mojobiri** [gimite/google-drive-ruby#290]
Is it possible to upload the local file to the specific folder in gDrive? I'm using v1.0.6

**Comment by mojobiri** [comment]
Closing this because found a workaround https://github.com/gimite/google-drive-ruby/issues/57#issuecomment-19166710

**Comment by gimite** [comment]
You can now use:
http://www.rubydoc.info/gems/google_drive/GoogleDrive%2FCollection:upload_from_file
to upload to a folder (collection) directly. I forgot which version it was added at, though. v1.0.6 is pretty old, so you may want to consider updating to the latest version.
