### ISSUE TITLE
How to get refresh token

### ISSUE THREAD

**Issue by chamnap** [gimite/google-drive-ruby#293]
I have been looking over the places, and I see similar issues. I hope there is a good documentation about this. 

I'm following this guide, https://github.com/gimite/google-drive-ruby/blob/master/doc/authorization.md#on-behalf-of-the-user-who-accesses-your-web-app-web-based-authorization. It works fine, except that I could not retrieve `refresh_token`. It always returns `nil`.

I also set `access_type` to `offline` in the `additional_parameters` of `Google::Auth::UserRefreshCredentials`.

Help wanted.

**Comment by gimite** [comment]
Do you access `refresh_token` after calling `credentials.fetch_access_token!`?

I haven't tried, but this document:
https://developers.google.com/identity/protocols/OAuth2WebServer#offline
contains this code snippet:

```ruby
auth_client.update!(
  :additional_parameters => {"access_type" => "offline"}
)
```

Maybe you can try that as well. It may be equivalent to specifying it in the constructor though...

**Comment by chamnap** [comment]
@gimite, Yeah. I did invoke `fetch_access_token!` before invoking `refresh_token`.

I do the following, and I'm able to retrieve the `refresh_token`. However, I'm able to get it only the very first time. 

```ruby
credentials = Google::Auth::UserRefreshCredentials.new(
  additional_parameters: {
    "access_type" => "offline",
    "include_granted_scopes" => "true"
  },
  client_id: ENV["GOOGLE_WEB_CLIENT_ID"],
  client_secret: ENV["GOOGLE_WEB_CLIENT_SECRET"],
  scope: [
    "https://www.googleapis.com/auth/drive",
    "https://spreadsheets.google.com/feeds/",
  ],
  redirect_uri: "http://localhost:3000/auth/google_drive/callback"
)
auth_url = credentials.authorization_uri.to_s

# on callback_controller
credentials.code = params[:code]
credentials.fetch_access_token!
credentials.refresh_token
```

After I get the `refresh_token`, and if I tried the above code again, it will return nothing. From your experience, is that normal?

**Comment by gimite** [comment]
It should be sufficient if you can get a refresh token once. After you get a refresh token, you can use this code (copied from the doc) any time to get an access token from the refresh token:

```ruby
credentials = ... same as above ...
credentials.refresh_token = refresh_token
credentials.fetch_access_token!
session = GoogleDrive::Session.from_credentials(credentials)
```

**Comment by chamnap** [comment]
@gimite, thanks for quick response.

Yeah, we could get that `refresh_token` only the first time. It's when google asks the user to approve the permission as shown in the screenshot. The problem is that for user who has authorized already, we won't have their `refresh_token`. The solution is to add `"prompt" => "consent"` inside `additional_parameters` hash. 

> consent: The user will always be prompted for consent, even if he has previously allowed access a given set of scopes.

<img width="451" alt="screen shot 2018-02-27 at 11 32 33 am" src="https://user-images.githubusercontent.com/407708/36710665-00ce19b0-1bb2-11e8-97c1-356a27afbf85.png">

**Comment by gimite** [comment]
I see, good to know.
