### ISSUE TITLE
Construct new session without config file but stringified json.

### ISSUE THREAD

**Issue by rushilagr** [gimite/google-drive-ruby#294]
Trying to create a session using a service account by calling -
```
GoogleDrive::Session.from_config
```
Passing the config file works perfectly, but i'm unable to use it by passing a json string directly.

I've tried copying the file's contents into a hash and converting it into a stringified json, but no luck.

Any tips? How to construct the IO object that's been written about in the code?

**Comment by gimite** [comment]
Session.from_config only takes a file path.

Session.from_service_account_key takes either a file path or an IO-like object:
http://www.rubydoc.info/gems/google_drive/GoogleDrive/Session#from_service_account_key-class_method
So you can pass StringIO.

**Comment by rushilagr** [comment]
Thanks!

**Comment by AydanSmith4** [comment]
could you show me an example of how you got i to work using a stringified json

**Comment by gimite** [comment]
Sorry for late.

```ruby
session = Session.from_service_account_key(StringIO.new(stringified_json))
```
