### ISSUE TITLE
"You need permission" trying to access spreadsheet

### ISSUE THREAD

**Issue by noctivityinc** [gimite/google-drive-ruby#296]
It appears that the spreadsheet is created correctly, however, when I try to visit the worksheet_feed_url I get a you need permission message every time.  It tells me to switch accounts but the account Im logged into is the account I verified with Oauth2.

Here is how Im setting this up:

```
credentials = Google::Auth::UserRefreshCredentials.new(
        client_id: Rails.application.secrets.google_oauth_client_id,
        client_secret: Rails.application.secrets.google_oauth_client_secret,
        scope: [
          "https://www.googleapis.com/auth/drive",
          "https://www.googleapis.com/auth/spreadsheets",
          "https://www.googleapis.com/auth/drive.file",
          "https://spreadsheets.google.com/feeds"
        ],
        access_token: session[:google_token],
        refresh_token: session[:google_refresh_token]
      )

      drive = GoogleDrive::Session.from_credentials(credentials)
```

where the google_token and refresh_token are returned from an Omniauth call.

**Comment by gimite** [comment]
What do you mean by "visit the worksheet_feed_url"? Did you fetch the URL programmatically, or did you open the URL on a browser? worksheet_feed_url is not meant to be opened on a browser, so it's possible that it cannot be opened in a browser. It requires OAuth instead of normal browser login.

**Comment by gimite** [comment]
Closing for now. Reopen if you still have any issue.
