### ISSUE TITLE
Update from file - Team Disk

### ISSUE THREAD

**Issue by ksuwala** [gimite/google-drive-ruby#299]
Hi guys, 

I try to find file by id `file = session.file_by_id("id")` (which is located on team drive) and it works, but things go wrong when i try to update this file via `file.update_from_string("test string")` it causes this error `Google::Apis::ClientError: notFound: File not found: XXXXXXXXXXXXXXXXXXXXX.` where X is an ID of this file

**Comment by gimite** [comment]
Thanks for the report. I will take a look.

**Comment by gimite** [comment]
Hopefully fixed with google_drive 2.1.10. I personally don't have team drive, so I cannot test it, though.
