### ISSUE TITLE
missing client_email

### ISSUE THREAD

**Issue by lsanc104** [gimite/google-drive-ruby#300]
Hi, I'm authorizing using a json key file, which was download from google api console. when I do GoogleDrive::Session.from_service_account_key(path_to_json_file) I get RuntimeError (missing client_email). Any help. Why?

**Comment by gimite** [comment]
The error sounds like the JSON file misses "client_email" field. Can you check if your JSON file contains "client_email" field? Service account key JSON file should look like this:

```json
{
  "type": "service_account",
  "project_id": "xxx",
  "private_key_id": "xxx",
  "private_key": "xxx",
  "client_email": "xxx@xxx.iam.gserviceaccount.com",
  "client_id": "xxx",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://accounts.google.com/o/oauth2/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/xxx.iam.gserviceaccount.com"
}
```

If it doesn't look like this, it is likely that your file is not a service account key JSON file. Make sure you followed steps [here](https://github.com/gimite/google-drive-ruby/blob/master/doc/authorization.md#on-behalf-of-no-existing-users-service-account) to download the file. Especially, make sure you selected "Service account key" in Step 3.
