### ISSUE TITLE
How to get authentication into production / CI?

### ISSUE THREAD

**Issue by StephanMeijer** [gimite/google-drive-ruby#305]
This library constantly asks me to login using my browser. How do I transfer my credentials to CI or production/staging?

**Comment by gimite** [comment]
The answer depends on whom you want your code to access Google Drive on behalf of. See this document for different options:
https://github.com/gimite/google-drive-ruby/blob/master/doc/authorization.md

Service account (the last one) would be a good option if it doesn't need to access Google Drive as a specific user.
