### ISSUE TITLE
How to create multiple worksheets ?

### ISSUE THREAD

**Issue by mchalise** [gimite/google-drive-ruby#306]
like by default worksheet [0] is created when the first spreadsheet is created. So what is the way to add multiple worksheets?  eg. worksheet[1], worksheet[2], so on..

**Comment by gimite** [comment]
Use Spreadsheet#add_worksheet:
https://www.rubydoc.info/gems/google_drive/GoogleDrive/Spreadsheet#add_worksheet-instance_method

e.g.:

```ruby
ss = session.spreadsheet_by_key("pz7XtlQC-PYx-jrVMJErTcg")
ws = ss.add_worksheet("Sheet 2")
```

**Comment by mchalise** [comment]
Thanks @gimite
