### ISSUE TITLE
Make google spreadsheet publicly accessible

### ISSUE THREAD

**Issue by rabinshrestha** [gimite/google-drive-ruby#307]
I am generating google spreadsheet with following code snippet

`
@google_drive_session ||= GoogleDrive::Session.from_config("google_drive_client_secret.json")
 @spreadsheet ||= @google_drive_session.create_spreadsheet(title = "Test Spreadsheet")
` 

With following google_drive_client_secret.json

`
{
  "client_id": "XXXXXXXXXXXX.apps.googleusercontent.com",
  "client_secret": "XXXXXXXXXXXXXXXXXXX",
  "scope": [
    "https://www.googleapis.com/auth/drive",
    "https://spreadsheets.google.com/feeds/"
  ],
  "refresh_token": "XXXXXXXXXXXx"
}
`

It generates spreadsheet on my google drive, but is only accessible to myself. How can I make this file accessible to everyone with link from code base?

Thanks in advance :)

**Comment by gimite** [comment]
See:
https://www.rubydoc.info/gems/google_drive/GoogleDrive/Acl#push-instance_method
