### ISSUE TITLE
"header field value cannot include CR/LF"

### ISSUE THREAD

**Issue by DaryMerckensGT** [gimite/google-drive-ruby#309]
https://bugs.ruby-lang.org/projects/ruby-trunk/repository/revisions/61359
https://bugs.ruby-lang.org/issues/14664#change-71384
https://github.com/ruby/ruby/commit/0078e40115fd53e2cafd4e8cfb6ff5fd7f87c3db
https://github.com/google/google-api-ruby-client/pull/648

Any way to integrate this fix into the gem?

**Comment by gimite** [comment]
google_drive uses google-api-client internally. Since https://github.com/google/google-api-ruby-client/pull/648 has been merged, wouldn't it be fixed if you use the latest version of google-api-client? Let me know if you still see similar issue, with sample code and error message.

**Comment by DaryMerckensGT** [comment]
Ah, yea. There are conflicts between 0.11 google-api-client dependencies and multiple other gems, but that's obviously not on you guys. I'm just gonna dynamically remove the ArgumentError raises from the HTTP ruby files because everything worked fine before those annoying commits were made.
