### ISSUE TITLE
Connection reset by peer - SSL_connect (Faraday::ConnectionFailed)

### ISSUE THREAD

**Issue by Dearest** [gimite/google-drive-ruby#311]
today I get this error
```
.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock': Connection reset by peer - SSL_connect (Faraday::ConnectionFailed)
```       

#### openssl:  LibreSSL 2.2.7    
-------

I try ruby 2.2.1, 2.3.0 , 2.4.1 still get this error,  who can help me ?

**Comment by gimite** [comment]
It means that HTTP connection to Google API has failed. Maybe your machine is not connected to Internet, or the connection is unstable?
