### ISSUE TITLE
Use with active storage

### ISSUE THREAD

**Issue by veritme** [gimite/google-drive-ruby#318]
Can I use this gem with active storage? and if possible, could you tell me how to do it?

**Comment by gimite** [comment]
google-drive-ruby doesn't have built-in Active Storage support. If Active Storage allows you to add your own storage implementation, you can write code to add its support.

Looks it does support Google Cloud Storage instead:
https://afreshcup.com/home/2017/07/06/introduction-to-active-storage-part-3-google-cloud-storage
Maybe it better suits such purpose in general?
