### ISSUE TITLE
How to make column as a read only.

### ISSUE THREAD

**Issue by rahul8sharma** [gimite/google-drive-ruby#320]

**Comment by gimite** [comment]
It is currently not supported by this library.

Should be possible once we switch to V4 API (#214), using this request:
https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/request#AddProtectedRangeRequest

You can directly hit the API for now.

Merging to #214.

**Comment by rahul8sharma** [comment]
Is there any update for new release?

**Comment by gimite** [comment]
It has been released as ver. 3.0.x. I believe you can do that by passing AddProtectedRangeRequest to this method:
https://www.rubydoc.info/gems/google_drive/3.0.1/GoogleDrive/Worksheet#add_request-instance_method

It would be nicer to add a method which does that directly similar to methods like this though:
https://www.rubydoc.info/gems/google_drive/3.0.1/GoogleDrive/Worksheet#set_text_format-instance_method
I'm happy to accept a pull request for it :)

**Comment by rahul8sharma** [comment]
I will create a PR for that but I need to check it first by using "add_request" method.

`sheet_id = file.worksheets.first.spreadsheet.id
 file.worksheets.first.add_request(
        {
          "requests": [
            {
              "addProtectedRange": {
                "protectedRange": {
                  "range": {
                    "sheetId": sheet_id,
                    "startRowIndex": 0,
                    "endRowIndex": 20,
                    "startColumnIndex": 0,
                    "endColumnIndex": 8,
                  },
                  "description": "Protecting total row",
                  "warningOnly": true
                }
              }
            }
          ]
        }
      )
`

The file is an object google drive file. This code is not working for read-only column.
Can you please help me to make it read-only.

**Comment by gimite** [comment]
The argument is an instance of Google::Apis::SheetsV4::Request or its Hash equivalent. So it should be `{"addProtectedRange": {...}}` instead. Also you should also call Worksheet#save as described in the document.

**Comment by rahul8sharma** [comment]
I have added this and not working. I am new for a google drive API so not able to access. Please help me to fix this.

`uploaded_file.worksheets.first.add_request(`
`  {`
`    "addProtectedRange": {`
`      "protectedRange": {`
`        "range": {`
`          "sheetId": sheet_id,`
`          "startRowIndex": 0,`
`          "endRowIndex": 20,`
`          "startColumnIndex": 0,`
`          "endColumnIndex": 8,`
`        },`
`        "description": "Protecting total row",`
`        "warningOnly": true`
`      }`
`    }`
`  }`
`)`

**Comment by rahul8sharma** [comment]
I got the issue. It is calling every time initialize() method.
1> First on add_request method
2> Second on save method

It is resetting the value of @v4_requests variable.

**Comment by gimite** [comment]
Yes, you must use the same instance of Worksheet for add_request and save, while Spreadsheet#worksheets returns a new instance every time. So you need to store `uploaded_file.worksheets.first` into a variable.

**Comment by rahul8sharma** [comment]
Yes, I did it. But getting bad request error.
``` ruby
sheet_id = uploaded_file.worksheets.first.sheet_id.to_s
a = uploaded_file.worksheets.first
a.add_request(
  {
    "addProtectedRange": {
      "protectedRange": {
        "range": {
          "sheetId": sheet_id,
          "startRowIndex": 3,
          "endRowIndex": 4,
          "startColumnIndex": 0,
          "endColumnIndex": 5,
        },
        "description": "Protecting total row",
        "warningOnly": true
      }
    }
  }
)

a.save
```

Google::Apis::ClientError: badRequest: Invalid requests[0]: No request set.

Another question: What is the "sheetId"

`sheet_id = uploaded_file.worksheets.first.sheet_id.to_s`
or
`sheet_id = uploaded_file.worksheets.first.spreadsheet.id`

**Comment by gimite** [comment]
sheetId should be Worksheet#sheet_id. Probably `sheet_id` as is, not `sheet_id.to_s`. You can see existing usage of add_request as reference:
https://github.com/gimite/google-drive-ruby/blob/master/lib/google_drive/worksheet.rb#L378

Maybe also the keys must be snake-case Symbol (e.g., :add_protected_range) not came-case String?

**Comment by rahul8sharma** [comment]
I am still getting the same error.
"Google::Apis::ClientError: badRequest: Invalid requests[0]: No request set."
My updated code is:

``` ruby
sheet_id = uploaded_file.worksheets.first.sheet_id

first_worksheet = uploaded_file.worksheets.first
first_worksheet.add_request(
  {
    "addProtectedRange": {
      "protectedRange": {
        "range": {
          "sheetId": sheet_id,
          "startRowIndex": 3,
          "endRowIndex": 4,
          "startColumnIndex": 0,
          "endColumnIndex": 5,
        },
        "description": "Protecting total row",
        "warningOnly": true
      }
    }
  }
)

first_worksheet.save
```

Do you feel anything missing here.

**Comment by gimite** [comment]
Nice! Just curious, what was wrong?

**Comment by altiusadmin** [comment]
Its saving. But still the cells are editable. Can u please help me here

**Comment by quangtt** [comment]
2020 here, above examples did not work for me. In my case, in request hash, it's just request name, no need `add_<request_name>`. And you must use snake_case for hash key name, not camelCase:

```
worksheet.add_request(
  update_dimension_properties: {
    range: {
      sheet_id: worksheet.sheet_id,
      dimension: 'COLUMNS',
      start_index: 0,
      end_index: 1
    },
    properties: {
      pixel_size: 65
    },
    fields: 'pixelSize'
  }
)
```
