### ISSUE TITLE
add new worksheet and change its position to first or any ? 

### ISSUE THREAD

**Issue by grfx1985** [gimite/google-drive-ruby#321]
is it possible to move the created worksheet inside a spreadsheet ? new one is always last. It would be fantastic to be able to move it as first or any position really. 
spreadsheet.worksheets is frozen as far as I can see ? any ideas ? 

Also is it possible to duplicate a whole worksheet ? I was not able to find any method for that ?

**Comment by gimite** [comment]
> is it possible to move the created worksheet inside a spreadsheet ? new one is always last. It would be fantastic to be able to move it as first or any position really.

It is currently not supported by the library. It will be possible using add_worksheet_v4 in #319:
https://github.com/gimite/google-drive-ruby/pull/319/files#diff-a725a64293a6e41f0998abaebc63be9aR91-R99

> Also is it possible to duplicate a whole worksheet ? I was not able to find any method for that ?

Not supported so far either, but it looks possible with this V4 API:
https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/request#duplicatesheetrequest

Both can be possible today if you directly hit V4 API.

**Comment by gimite** [comment]
It is now officially supported with google_drive 3.0.0:

```ruby
spreadsheet.add_worksheet('New worksheet', index: 0)
```
