### ISSUE TITLE
consumes a LOT of memory

### ISSUE THREAD

**Issue by MaG21** [gimite/google-drive-ruby#323]
google-drive-ruby consumes a lot of memory when working with spreadsheets greater than 2k rows. Memory KEEPS growing and growing after doing repetitive basic operations like: Insert, update and save (!). Definitely looks like a memory leak.

Similar to #281

**Comment by gimite** [comment]
Thanks for the report. As you pointed, the issue looks the same as one discussed in #281. So let me close this one. See https://github.com/gimite/google-drive-ruby/issues/281#issuecomment-397499352 for the current status of the issue. The v4 migration (#214) is currently in progress.

**Comment by gimite** [comment]
BTW One potential workaround is to split your change to smaller chunks and call `save` for each chunk.

**Comment by MaG21** [comment]
Google has a write quota, saving small chunks won't help in my particular case.

Honestly I'm going to use Python's implementation https://github.com/burnash/gspread which seems a bit maturer and supports  V4. I personally avoid python whenever possible (for unrelated reasons), but for now, it seems the best option available.

Have you guys considered porting some functionality back to Ruby? for example, the following comes really really handy:
```python
# Get all values from the first column
values_list = worksheet.col_values(1)
```

Thanks

**Comment by gimite** [comment]
> Have you guys considered porting some functionality back to Ruby? for example, the following comes really really handy:

It is a bit more verbose, but doesn't look so bad to me:

```ruby
values_list = (1..ws.num_rows).map{ |r| ws[r, 1] }
```

Since we already have Worksheet#rows, it may be good to have Worksheet#cols as well though, then you could write:

```ruby
values_list = ws.cols[0]
```

Let me know if you have any other features in the Python library you find useful.

**Comment by MaG21** [comment]
wow, that's delicious:

```ruby
value_list = ws.cols[0]

# vs

values_list = (1..ws.num_rows).map{ |r| ws[r, 1] }
```

> Let me know if you have any other features in the Python library you find useful.

👍
