### ISSUE TITLE
Any way to get a `=hyperlink()`s URL or a cells formula/function out of a spreadsheet?

### ISSUE THREAD

**Issue by arye-dov-eidelman** [gimite/google-drive-ruby#326]
Any way to get a `=hyperlink()`s URL or a cells formula/function out of a spreadsheet. or is that beyond the scope of this gem?

**Comment by gimite** [comment]
Here it is:
https://www.rubydoc.info/gems/google_drive/GoogleDrive/Worksheet#input_value-instance_method
