### ISSUE TITLE
Option to turn off infinite timeout

### ISSUE THREAD

**Issue by dnprock** [gimite/google-drive-ruby#330]
During recent Google Sheets outage on 01/29/19, I notice that calls in google-drive-ruby doesn't timeout.

I found the below code to set timeout to infinite:

https://github.com/gimite/google-drive-ruby/blob/6496049c70731d95f59030e15727743f4e4966ed/lib/google_drive/api_client_fetcher.rb#L28

I suggest making it infinite if code doesn't set it.

**Comment by gimite** [comment]
Sorry to be late. I believe it is already implemented as you suggested because it overrides with the given `client_options` afterwards. Let me know if I miss anything.
