### ISSUE TITLE
Adding formulae with new cell references on new rows

### ISSUE THREAD

**Issue by arnoldmarunda** [gimite/google-drive-ruby#333]
I am successfully using **input_value**  to copy a formula from the last row in a spreadsheet  cell that I need applied to the same cell in the next row. 
However, the cell references do not increment e.g `=A1+B1 ` in the first row remains `=A1+B1` in the second row instead of becoming `A2+B2`

Is there a way to resolve this?

**Comment by gimite** [comment]
Sorry for late.

Looks like you can do that by directly issuing CopyPasteRequest:
https://www.rubydoc.info/github/google/google-api-ruby-client/Google/Apis/SheetsV4/Request#copy_paste-instance_method

e.g.:

```ruby
ws = session.spreadsheet_by_url("...").worksheets[0]
ws.add_request({
  copy_paste: {
    source: {
      sheet_id: ws.sheet_id,
      start_row_index: 0,
      start_column_index: 2,
      end_row_index: 1,
      end_column_index: 3,
    },
    destination: {
      sheet_id: ws.sheet_id,
      start_row_index: 1,
      start_column_index: 2,
      end_row_index: 2,
      end_column_index: 3,
    },
  },
})
ws.save
```

Note that row/column indices in the API is 0-origin (different from normal google_drive API). Maybe I should provide a method in Worksheet to wrap it...

**Comment by arnoldmarunda** [comment]
Hi @gimite you were not late, I are 🥇  - I posted over weekend.

Thanks, the snippet you provided works great. 

Many thanks for a great gem, very useful.
