### ISSUE TITLE
How read/write specify properties on worksheet?

### ISSUE THREAD

**Issue by tit** [gimite/google-drive-ruby#337]
```ruby
require 'google_drive'

session = GoogleDrive::Session.from_service_account_key 'key.json'
spreadsheet = session.spreadsheet_by_key 'spreadsheet_key'
worksheet = spreadsheet.worksheets.first

# I want to change grid_properties here

worksheet.save
```

How I can read and write some worksheet properties before save?
https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/sheets#gridproperties
I need read and write hideGridlines property.

**Comment by gimite** [comment]
Use https://www.rubydoc.info/gems/google_drive/GoogleDrive%2FWorksheet:add_request which accepts any Google::Apis::SheetsV4::Request.
