### ISSUE TITLE
Upload directly from program.

### ISSUE THREAD

**Issue by AydanSmith4** [gimite/google-drive-ruby#340]
I was wondering how I would upload a file to google drive that is generated within the program. In my case I am generating a csv file and then want to upload it to google drive.

**Comment by gimite** [comment]
Does this example code help?:
https://github.com/gimite/google-drive-ruby#example-to-readwrite-files-in-google-drive
See "Uploads a local file" part. It also has upload_from_string and upload_from_io methods. See the API doc for details:
https://www.rubydoc.info/gems/google_drive/GoogleDrive/Session

**Comment by AydanSmith4** [comment]
yeah, thanks
