### ISSUE TITLE
How can I get the link to a file

### ISSUE THREAD

**Issue by AydanSmith4** [gimite/google-drive-ruby#341]

**Comment by AydanSmith4** [comment]
I need to get the link to a file so I can add it in to a message

**Comment by gimite** [comment]
I believe this method should work:
https://www.rubydoc.info/gems/google_drive/GoogleDrive/File#human_url-instance_method

**Comment by AydanSmith4** [comment]
The example link is deprecated.

**Comment by AydanSmith4** [comment]
Do you have an example of using it in an actual program

**Comment by AydanSmith4** [comment]
It says to Use GoogleDrive::Session#files or GoogleDrive::Session#file_by_title to get this object but the # just comments out the rest of the line

**Comment by AydanSmith4** [comment]
I solved my issue. For others I created the session and then used:
test = session.file_by_title("title of file")
link = test.human_url
puts link

**Comment by gimite** [comment]
That's correct. FYI GoogleDrive::Session#files is a standard way in Ruby to refer to an instance method called files of a class GoogleDrive::Session.

And thanks for pointing to a deprecated example in the doc. The method itself should return a valid URL.
