### ISSUE TITLE
How can I modify sharing permissions using this API?

### ISSUE THREAD

**Issue by AydanSmith4** [gimite/google-drive-ruby#342]

**Comment by AydanSmith4** [comment]
For your info, I am trying to make it so that anyone within my organization can view the file

**Comment by gimite** [comment]
See https://www.rubydoc.info/gems/google_drive/GoogleDrive/Acl#push-instance_method

**Comment by AydanSmith4** [comment]
I'm having trouble accessing the spreadsheet.acl.push. When I use GoogleDrive::Spreadsheet.acl I get "undefined metheod: acl"

**Comment by gimite** [comment]
Can you share me your code? Note that you have to call acl method against an instance of GoogleDrive::Spreadsheet, not a class itself.

**Comment by AydanSmith4** [comment]
require 'google_drive'

session = GoogleDrive::Session.from_config('credentials.json')
session.upload_from_file("testtwo.csv", "curious", convert: true)

test = session.file_by_title("test")
link = test.human_url
link ["edit?usp=drivesdk"] = "preview"
puts link

#here is the code I have for file permissions
spreadsheet = GoogleDrive::Spreadsheet
spreadsheet.acl.push({type: "domain", domain: "c2fo.com", role: "reader"})

**Comment by AydanSmith4** [comment]
also on a random note, can I upload to a specific folder using session.upload_from_file, then I would be able to just change folder permissions in drive

**Comment by AydanSmith4** [comment]
never mind I figured it out. 

spreadsheet = session.file_by_id(id#)
spreadsheet.acl.push({type: "domain", domain: "domain name", role: "reader"})
