### ISSUE TITLE
Returning nil from Session#files when block given

### ISSUE THREAD

**Issue by woarewe** [gimite/google-drive-ruby#344]
Hello, I use call Session#files with block and it returns nil. I inspected source code and found [reason](https://github.com/gimite/google-drive-ruby/blob/master/lib/google_drive/session.rb#L599)
I wanna get all files of folder and I prefer functional style, so I tried to do so:

```ruby
def all_files
  session.files(&:itself) # nil
end
```
Instead of this:

```ruby
def all_files
  [].tap { |ary| session.files { |file| ary << file } } # [<File#1>, <#File2>], but very ugly
end
```

I think, will be better if method ```files``` with passed block file will return all processed files.
If you are agree with me I can implement this.
Thanks for attention.

**Comment by gimite** [comment]
Sorry for late. You can still write like this:

```ruby
session.enum_for(:files).to_a
```

It may be OK to return all files as an Array as its return value as well, but the method must keep all file objects in memory then, which may be a concern in terms of memory consumption. Would be rare that it becomes an issue though.

Also, note that enumerating all files (in either way) can take very long if the number of files in the account is large.

**Comment by woarewe** [comment]
Thanks a lot, sorry for so big pause.
