### ISSUE TITLE
Is there an easy way to test this?

### ISSUE THREAD

**Issue by patriciobi** [gimite/google-drive-ruby#355]
I want to know if there's an easy way to stub or mock the worksheet functionality to test a module I've made with this gem.

**Comment by gimite** [comment]
Sorry for not responding to this since I was busy recently. In case you still want to know the answer, no, the library does not provide any fakes for its classes. You can write your own or use any general mocking library for Ruby to create one.

**Comment by Drowze** [comment]
In case anyone else come here looking for this, I've written a mock class to run my gem's tests:
https://github.com/Drowze/aspirebudgeting_ruby/blob/master/spec/support/google_drive_mock.rb

As of now it's a bit specialized for my purposes, but should be easy to read and edit to use on your own project.
