### ISSUE TITLE
Please release gem to permit new version google-api-client

### ISSUE THREAD

**Issue by nagachika** [gimite/google-drive-ruby#362]
Hi, thank you for your work for google_drive.gem.

Is there any planned release date for new version (maybe 3.0.4 or so)?
We want to use newer version of google-api-client (say 0.36.x) in our projects, but google_drive-3.0.3 depend on `< 0.31.0`.
I've found that the current master has more relaxed dependency (`< 0.37.0`). Please concider the release new version of google_drive.gem.
Thanks.

**Comment by gimite** [comment]
Sorry I haven't released its new version for a while. I have just pushed google_drive 3.0.4.

**Comment by nagachika** [comment]
I'm very appreciated for the new release!
