### ISSUE TITLE
LoadError (cannot load such file -- google/apis/drive_v3)

### ISSUE THREAD

**Issue by abmBispo** [gimite/google-drive-ruby#364]
### SCENARIO
I'm currently developing a standalone Ruby project to run over AWS Lambda service. My intention with this choice is reduce complexity and cost for backend application. In order to deploy the scripts to AWS Lambda I had to bundle all gems into `vendor` folder - Lambda's requirements, it's impossible to install anything, gems for exemple, while executing function or setup any gem before function execution. So I tried this out (bundle all gems into `vendor` folder and execute the scripts) and all was going right until I fell in a error that I simply couldn't find solution in the internet once the error label was too much not explanatory. Now when I finaly could solve it, I could not think any other better place than this to report my experience and how I've solve it.

### PROBLEM
To make my scripts consume gems from `vendor` folder instead of system path (inexistent in Lambda for the most of gems) I had to update the `$LOAD_PATH` global in this way:

```ruby
load_paths = Dir['vendor/ruby/2.5.0/**/lib*']
$LOAD_PATH.unshift(*load_paths)
```
I have already used this snippet before in some projects I developed to run in Lambda: it basicly says that there is a new folder from where the gems can now be loaded - that is, `#{gem name}/lib#{semver}`. But in this case I was getting that error, here the traceback:

```
irb(main):004:0> require 'google_drive'
Traceback (most recent call last):
       13: from /home/alanborges/.rbenv/versions/2.5.0/bin/irb:11:in `<main>'
       12: from (irb):4
       11: from /home/alanborges/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
       10: from /home/alanborges/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        9: from /home/alanborges/projects/smartalkdev/smartalk-omie/vendor/ruby/2.5.0/gems/google_drive-3.0.4/lib/google_drive.rb:7:in `<top (required)>'
        8: from /home/alanborges/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        7: from /home/alanborges/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        6: from /home/alanborges/projects/smartalkdev/smartalk-omie/vendor/ruby/2.5.0/gems/google_drive-3.0.4/lib/google_drive/session.rb:12:in `<top (required)>'
        5: from /home/alanborges/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        4: from /home/alanborges/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        3: from /home/alanborges/projects/smartalkdev/smartalk-omie/vendor/ruby/2.5.0/gems/google_drive-3.0.4/lib/google_drive/api_client_fetcher.rb:6:in `<top (required)>'
        2: from /home/alanborges/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        1: from /home/alanborges/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
LoadError (cannot load such file -- google/apis/drive_v3)
```

### SOLUTION
The solutions for this problem is really simple: the script couldn't find the necessary `google/apis/drive_v3` gem, as we have in `google_drive-3.0.4/lib/google_drive/api_client_fetcher.rb`:

```ruby
# Author: Hiroshi Ichikawa <http://gimite.net/>
# The license of this source is "New BSD Licence"

require 'net/https'
require 'uri'
require 'google/apis/drive_v3' # HERE
require 'google/apis/sheets_v4'
Net::HTTP.version_1_2

module GoogleDrive
  class ApiClientFetcher
    class Response
      def initialize(code, body)
        @code = code
        @body = body
      end

      attr_reader(:code, :body)
    end
    ...
  end
end
```

Searching for this gem I've found it's [source files here](https://github.com/googleapis/google-api-ruby-client/tree/master/generated/google/apis/drive_v3), and the first thing I noticed was that this very source files wasn't inside `../**/lib*` folder but in `/**/generated*`. Thus the only thing I had to do was add this path to that snippet, getting like this:

```ruby
load_paths = Dir['vendor/ruby/2.5.0/**/lib*', 'vendor/ruby/2.5.0/**/generated*']
$LOAD_PATH.unshift(*load_paths)
```

Now everything just works fine!

Viva Cristo Rei.

**Comment by gimite** [comment]
Thanks for the report. It would be useful for people with similar situation. Let me close this issue because it looks you have already found a solution, and I guess no further help/change is necessary from the library side. But feel free to reopen if you have any request to the library regarding this.
