### ISSUE TITLE
[Feature request] Ability to set width of a Google Sheets column

### ISSUE THREAD

**Issue by bachand** [gimite/google-drive-ruby#370]
I love this library!

I'm using it to upload daily metrics data to a Google Sheet.

It would be valuable if I could specify the width of a column.

That way I don't need to manually edit the sheet to make the text easier to read.

**Comment by gimite** [comment]
I guess it's possible using:
https://www.rubydoc.info/gems/google_drive/GoogleDrive/Worksheet#add_request-instance_method
assuming Google Sheets API provides a request type for it (which I haven't checked).

**Comment by bachand** [comment]
This worked, thank you! `Google::Apis::SheetsV4::AutoResizeDimensionsRequest` is the key 👍

**Comment by quangtt** [comment]
For whose also looking for an example, this is working for me:
(This setting a fixed size for column(s), I tried auto-resize but didn't work)

```
worksheet.add_request(
  update_dimension_properties: {
    range: {
      sheet_id: worksheet.sheet_id,
      dimension: 'COLUMNS',
      start_index: 0,
      end_index: 1
    },
    properties: {
      pixel_size: 65
    },
    fields: 'pixelSize'
  }
)
```

**Comment by mhluska** [comment]
Here's an actual example:

```
worksheet.add_request(
  auto_resize_dimensions: {
    dimensions: {
      sheet_id: worksheet.sheet_id,
      dimension: 'COLUMNS',
      start_index: 0,
      end_index: columns.length - 1
    }
  },
)
```
