### ISSUE TITLE
Create new release to update the gem google-api-client

### ISSUE THREAD

**Issue by 4brunu** [gimite/google-drive-ruby#374]
Hello,

The last published version of this gem, depends on `google-api-client  >= 0.11.0, < 0.37.0`
https://rubygems.org/gems/google_drive/versions/3.0.4

Could you please release an update with the version from the master branch?

Thanks 👍

**Comment by gimite** [comment]
Done. Sorry for late. I has been a while since google-api-client introduced a backward incompatible change, so I updated the dependency to `google-api-client >= 0.11.0, < 1.0.0` for now.

**Comment by 4brunu** [comment]
No problema, thank you for your help! 😊
