### ISSUE TITLE
The dependency `google-api-client` is deprecated

### ISSUE THREAD

**Issue by FunnyHector** [gimite/google-drive-ruby#392]
Reference: https://github.com/googleapis/google-api-ruby-client/blob/master/google-api-client/OVERVIEW.md

`google-api-client` is deprecated. By a quick look I think we could instead just use `google-apis-drive_v3`.

**Comment by DannyBen** [comment]
Any chance this can be looked at soon? Hopefully the proposed PR fixes the issues transparently, without side effects.

**Comment by gimite** [comment]
Sorry for late. Merged.
