### ISSUE TITLE
The last version of gem doesn't support ruby 3.0.0

### ISSUE THREAD

**Issue by dzmitry-aleinik-itechart** [gimite/google-drive-ruby#395]
The Kernel#open was disabled since 3.0.0, you can change it for URI#open instead.
https://github.com/gimite/google-drive-ruby/blob/master/lib/google_drive/session.rb#L85

**Comment by gimite** [comment]
Sorry for late. But I couldn't find information about deprecation/disabling of Kernel.#open:
https://ruby-doc.org/core-3.0.0/Kernel.html#method-i-open

I was also able to use Kernel.#open successfully in Ruby 3.0.0 without any errors/warnings. Can you provide a pointer to the disabling?

**Comment by DannyBen** [comment]
I can also confirm that the gem works for me in Ruby 3.0.

**Comment by gimite** [comment]
Thanks! Closing this for now. Feel free to reopen if you have any information.
