### ISSUE TITLE
How can i get a file by id

### ISSUE THREAD

**Issue by sebastianorellanav** [gimite/google-drive-ruby#416]
Hello!

I want to get a file of google drive by it's id but in the documentation only appears Collection.file_by_title and Collection.files methods. 

Is this possible?

**Comment by sroller** [comment]
https://developers.google.com/sheets/api/quickstart/ruby

describes how to access a Google Sheet by id. Does that help?

**Comment by sebastianorellanav** [comment]
I already solved it. 
I used the Session.file_by_id method and it worked. However it is strange that this method does not appear in the documentation.
Thanks for the reply anyways.
