### ISSUE TITLE
What about other api methods like Changes: list

### ISSUE THREAD

**Issue by dcdieci** [gimite/google-drive-ruby#44]
Hi,

I think it wouldn't be nice to have kind of an abstract method which is able to make request to the api with the api_method as parameter. Since the drive api provides a bunch more methods than available in the gem I start wondering how to make use of them in combination with this gem.
For instance I dont want to make calls against the api everytime I need the files of my account. I d rather prefer storing all the files in an array in the database and serialize it. The drive api has a method called changes.list which return changes, so whenever i get something returned i can update my stored array, otherwise just use it from the db, which is much fast than requesting collections or files all the time.
So currently I dont any chance to do it with this gem, but maybe I am wrong?

best,
phil

**Comment by gimite** [comment]
google_drive 1.0.0 or later uses Drive API, so you can call arbitrary Drive API methods via:
http://www.rubydoc.info/gems/google_drive/GoogleDrive/Session#drive-instance_method
Note that google_drive 1.x.x uses Drive API V2, and google_drive 2.x.x (currently in beta) uses Drive API V3, which provides completely different API.
