### ISSUE TITLE
Presentation download in other format than PNG

### ISSUE THREAD

**Issue by simontesar** [gimite/google-drive-ruby#64]
Currently, a presentation can only be downloaded in the PNG format. Event the text/plain format returns a PNG picture as binary string. The result contains only the first page of the presentation.

Is possibly to implement a download in atleast the PDF-Format with all pages?

**Comment by gimite** [comment]
google_drive 1.x.x supports exporting with export_as_file method. Confirmed that I can convert presentation to .pptx and .pdf. 

".pptx" extension is not recognized in google_drive 1.x.x, so you need to specify the content_type explicitly:
```ruby
presentation = session.file_by_id("...")
presentation.export_as_file("out.pptx", content_type: "application/vnd.openxmlformats-officedocument.presentationml.presentation")
```
It will be fixed in 2.0.0.
