### ISSUE TITLE
Is there a way to get cells by name

### ISSUE THREAD

**Issue by dasheck0** [gimite/google-drive-ruby#94]
Excel provides accessing cells by names. You can name cells (A1 => RevenueForCurrentYear). I wonder if there is a feature currently in the gem, which yields the value of the cell when providing the name. 

If not does google spreadsheet supports this via its API or is there no way to add this feature to the gem?

Best regards

**Comment by lastobelus** [comment]
Any update on this? Google sheets doess definitely now have [named ranges](https://support.google.com/docs/answer/63175?hl=en).

**Comment by gimite** [comment]
I'm not sure if there's API to support named ranges. Let me know if you find it.

**Comment by lastobelus** [comment]
I've decided to jump into the world of apps scripts and use the rest execution api and have my server talk to that.
