### ISSUE TITLE
Switch to google drive SDK

### ISSUE THREAD

**Issue by dasheck0** [gimite/google-drive-ruby#96]
Hi,

I read in one of your issues that you plan on switching to google drive SDK. I really look forward to it since some of the features are broken (Uploading/Updating spreadsheets for example). 

Do you already have an public accessable branch, that I can work with? How far is the overall progress at the moment?

best regards

**Comment by basti** [comment]
@gimite does the latest gem version now use Google Drive API? I still see in the code some of the old URLs using Documents List API that will be discontinued on April 20, 2015.

**Comment by gimite** [comment]
Yes, ver 1.0.0 uses Google Drive API. I kept some methods which returns URL for document list API for backward compatibility, but it should no longer hit document list API implicitly. Let me know if you find a case where it still uses document list API.

**Comment by basti** [comment]
Thanks for clarifying that and thanks for building a great gem. :smiley:
